### ISSUE TITLE
Multi-Label classification

### ISSUE THREAD

**Issue by Wronskia** [snorkel-team/snorkel#1041]
Thank you for the very interesting work!

I was wondering if Snorkel is planning to extend its features to multilabel classifications? e.g., Semantic Role Labelling task.

Thanks a lot

**Comment by rtygbwwwerr** [comment]
I was wondering as well

**Comment by bhancock8** [comment]
Multilabel classification isn't currently on our near-term roadmap, but we do accept PRs! :)

**Comment by ajratner** [comment]
Closing for now, but as @bhancock8 said we love PRs!

**Comment by rjurney** [comment]
@ajratner Do you have a sense of what would be involved in adding multi-label support to Snorkel? This interests me.

**Comment by rjurney** [comment]
@bhancock8 @ajratner I’m interested in doing this work for 0.9 if you can provide me with some guidance on what would be involved.

**Comment by hpeiyan** [comment]
Also interested in this feature. Thanks for your work. @ajratner

**Comment by bhancock8** [comment]
Great

**Comment by bhancock8** [comment]
Great question! We appreciate the offer to contribute! In general, you can naively support multi-label problems by just treating each label as a separate binary classification problem. You could also then make these each a part of a multi-task classifier if you want information sharing between labels. To get multi-label support into the LabelModel would require more thought and work, since it would introduce a new type of dependencies between classes. That's not on our immediate roadmap, but it's good to know that there's interest here!

**Comment by rjurney** [comment]
@bhancock8 Thanks, it sounds like multi output is what I need.

**Comment by hpeiyan** [comment]
@bhancock8 Thanks for your prompt.

**Comment by ajratner** [comment]
I'm going to close this for now; as @bhancock8 summarized above, the basic approach is just to treat a $k$-wise multi-label classification problem as $k$ separate binary tasks.  These can also share / jointly learn representations using a multi-task learning approach as supported in Snorkel!

As for the label model- using $k$ versions of the basic label model will be fine in the case where there are no complex logical constraints between the different labels (e.g. in the vanilla multi-label classification setting where each data point could have any subset of the $k$ labels)

**Comment by eggie5** [comment]
My core problem is a multi-label problem, but my snorkel data, form the `LabelModel` is inherently single-label. What is the prevailing recommendation to do multi-label w/ Snorkel?

For a given, k-wise multi-label problem: 

1. Generate `k` binary datasets w/ `LabelModel`
2. Train `k` seperate binary classifiers
3. At inference/prediction time pass `x` though the `k` classifiers and get scores.

Is this what the current recommendation is?

**Comment by Manel-Hik** [comment]
Hi Snorkel Team,
Is there any Snorkel new feature that could help with multi-label classification problem?
Thanks

**Comment by bhancock8** [comment]
Hi @Manel-Hik, the responses above are still the recommended way to do multi-label classification with this library.
