### ISSUE TITLE
what's the bayesnet's advantage as the GenerativeModel?

### ISSUE THREAD

**Issue by aling1472** [snorkel-team/snorkel#1067]
i'm wandering why not just use the LFs output as features to train a svm model to predict relations?

**Comment by rtygbwwwerr** [comment]
Because we don't know the True labels of training data, we have to use generative Model gain some credible pseudo labels.

I think snorkel just learn a set of combination weights of LFs(like stacking ensemble, each LF can be seen as a week classifier) without LFs dependencies. Fortunately, we can use dependency factors model relationships among LFs, this should be the main advantage of snorkel on sample model ensemble

**Comment by paroma** [comment]
Thanks for your question! We now have a community forum on [Spectrum](https://spectrum.chat/snorkel/) for discussions like these!

Overall, using LFs as features doesn't generalize to use richer features that downstream ML models can learn from. 

The [Training Classifiers with Natural Language Explanations](https://arxiv.org/abs/1805.03818) paper also compares directly to using LF outputs as features. 

#946 has a discussion around why we don't usually have LFs as features

**Comment by ajratner** [comment]
@rtygbwwwerr thanks for the answer!

To quickly summarize on why we in general don't just use the LFs as features in a model as our final classifier:
- *(1) Generalization:* In most of the problems we tackle with Snorkel, the LFs won't cover a lot of the data (and trying to get them to do this with high enough precision would be a very burdensome process...).  Instead, we want to use them to supervise some end discriminative model (e.g. a deep net) that has many more features and can generalize to new data!
- *(2) Labeled data:* To train a model defined over the LFs, we'd need labeled data- in general we don't have a lot of this, hence why we follow the Snorkel pipeline as proposed

Either way, @aling1472  in the end, you should do whatever is best for your setting- if you have a fairly simple, low-data-complexity problem, writing a few LFs and then training an SVM with hand-labeled data could work fine (this is just traditional feature engineering + supervised learning!)

Closing this for now, and it's marked as Q&A to be easily discoverable
