### ISSUE TITLE
Intro_Tutorial_2: cannot import name 'compile_relation_feature_generator'

### ISSUE THREAD

**Issue by achal648** [snorkel-team/snorkel#1083]
ImportError                               Traceback (most recent call last)
<ipython-input-12-f0f475f62e96> in <module>
----> 1 from snorkel.annotations import load_gold_labels
      2 
      3 L_gold_dev = load_gold_labels(session, annotator_name='gold', split=1)

~\AppData\Local\Continuum\anaconda3\envs\snorkel\lib\site-packages\snorkel\annotations.py in <module>
     11 from sqlalchemy.sql import bindparam, select
     12 
---> 13 from snorkel.features import get_span_feats
     14 from snorkel.models import (
     15     GoldLabel, GoldLabelKey, Label, LabelKey, Feature, FeatureKey, Candidate,

~\AppData\Local\Continuum\anaconda3\envs\snorkel\lib\site-packages\snorkel\features\__init__.py in <module>
     10 from .entity_features import *
     11 from .generic_features import get_feats_from_matrix
---> 12 from .relative_features import (
     13         get_document_relative_frequency_feats,
     14         get_first_document_span_feats,

~\AppData\Local\Continuum\anaconda3\envs\snorkel\lib\site-packages\snorkel\features\relative_features.py in <module>
     10 import re
     11 
---> 12 from treedlib import compile_relation_feature_generator
     13 
     14 from snorkel.features.entity_features import compile_entity_feature_generator, get_ddlib_feats

ImportError: cannot import name 'compile_relation_feature_generator'

**Comment by paroma** [comment]
We're in the middle of a big refactor and will release the upgrade this summer! We expect the upgrade to address this issue

**Comment by bhancock8** [comment]
Snorkel v0.9 was released today with a fresh batch of tutorials that have been thoroughly tested! Give these a try. We recommend starting with the "Getting Started" walkthrough: https://www.snorkel.org/get-started/.
