### ISSUE TITLE
Matching chunks in candidate extraction

### ISSUE THREAD

**Issue by phosseini** [snorkel-team/snorkel#1085]
@stephenbach @ajratner @bhancock8 I want to match chunks (e.g. Noun Phrases (NPs) and Verb Phrases (VPs)) in documents when I extract candidates. Let's say I want to find candidates of a relation called REL in documents. And REL has two arguments, A and B, respectively. A and B in my case are either NP or VP. 

I'm wondering if I should define a matcher myself? (as far as I know there is no such matcher in the Snorkel's matcher.) Considering the fact that I'm using CoreNLP and I have chunk labels --from binarizedParseTree in the output of CoreNLP (I added a piece of code to the StanfordCoreNLPServer to extract chunks from the output of CoreNLP)-- I just wonder how I should implement this? I think the most confusing part for me is that all the information of sentences is being stored at token/work level and I have hard time figuring out how to store the chunks information in DB in a way that it could be used in a matcher function.

`UPDATE:` As of now, I added a new column named `chunk_tags` to the `Sentence` which keeps the chunk tag of tokens in a sentence. For example, if we have a sentence like `"this is a sentence"` I convert it to a string like `" - - NP NP"` where NPs are for the "a" and "sentence" which belong to NPs in the sentence. Then I store this string in DB to be able to use it for candidate extraction using regex --this is what I hope would work. I want to make sure that I am not reinventing the wheel here and if Snorkel has a capability for matching chunks?

`YET ANOTHER UPDATE!` I solved my problem and I'd be happy to share my code. But I'm still looking for an answer to my question. I'm not sure if the way I solved my problem is the most *efficient* way and whether I reinvented the wheel or not!

> And, since there is no chunker in Spacy, should I use other tools like CoreNLP in my matcher function?
> [Edit]: I just realized that Snorkel supports CoreNLP. And, I could successfully use the CoreNLP chunker, but I still do not know how I can use the chunker labels to have a matcher for extracting NP/VP as candidates using the CandidateExtractor.

**Comment by henryre** [comment]
Hi @phosseini, Snorkel v0.9 has native tooling for the latest version of spaCy which supports noun phrase chunking (https://spacy.io/usage/linguistic-features#noun-chunks). We don't rely on a fixed DB schema, so you can be a lot more flexible with how you store candidates. As an FYI, we've moved the information extraction version of Snorkel (v0.7) to https://github.com/snorkel-team/snorkel-extraction. Feel free to reopen this PR there! It would be great if you could share your code so that we or others could collaborate.
