### ISSUE TITLE
Email classification : ham and spam

### ISSUE THREAD

**Issue by aiexplorations** [snorkel-team/snorkel#1087]
I'm trying to determine how to define candidate classes for an toy problem on email classification (ham / spam). The email text content is stored as a some "input.tsv" file, much like the example file "articles.tsv" that's in the intro tutorials (spousal relationship extraction). 

How do I build a candidate class that's appropriate to this problem?

Entity extraction is one element of the Snorkel API that isn't explained in much detail in the documentation or in the Mobilize Center videos. Hence my request. Please help.

PS: The "gold labels" in the "input.tsv" file are in the second column after the email content, separated by the tab space. Presumably this has to be extracted into a separate file, and then brought in?

**Comment by paroma** [comment]
We are in the middle of a big refactor for the code which we will release later this summer. The update should address this issue

**Comment by henryre** [comment]
To add a bit more detail: one of our main tutorials will be a ham/spam document classification problem, so that should give you a lot to work with.

**Comment by bhancock8** [comment]
Snorkel v0.9 was released today with exactly the tutorial you're looking for! For a quick overview of how to approach a spam classification problem like this with Snorkel, check out the "Getting Started" walkthrough: https://www.snorkel.org/get-started/. After that, there are three additional tutorials that go into greater detail on how to apply labeling functions, transformation functions, and slicing functions to improve performance further or give a clearer picture into your model's performance. If you have any thoughts after trying it out, let us know on the Snorkel community forum: https://spectrum.chat/snorkel?tab=posts.
