### ISSUE TITLE
When I stored the contents of spacy decomposition into sqlite, I got garbled.

### ISSUE THREAD

**Issue by HAIDIRAO** [snorkel-team/snorkel#1099]
![TIM截图20190420145743](https://user-images.githubusercontent.com/49801150/56453981-b37e3c80-637c-11e9-9c46-a286af224e40.png)

**Comment by henryre** [comment]
Hi @HAIDIRAO, Snorkel v0.9 has native tooling for spaCy and we don't rely on a fixed DB schema anymore. That means you can be a lot more flexible with how you operate over spaCy objects. There's an example of using spaCy for LF preprocessing in our new [intro tutorial](https://www.snorkel.org/use-cases/01-spam-tutorial#d-lfs-with-complex-preprocessors). As an FYI, we've moved the information extraction version of Snorkel (v0.7) to https://github.com/snorkel-team/snorkel-extraction. Feel free to reopen this issue there!
