### ISSUE TITLE
Snorkel.DB Issues / Queries

### ISSUE THREAD

**Issue by skk123123** [snorkel-team/snorkel#1101]
I am working on a project that requires generation of automatic labels for structured datasets. We are working with data that is well defined in columns.

Our main challenge so far has been trying to get data in the format understood by Snorkel (i.e. the Candidate / Context / Span structure).

Snorkel.db is already loaded with a lot of data before the workshop example even commences.

Do I need to have the entire schema ready and populated in a db by writing my own code for this since the workshop example assumes a populated db ?

In this regard, I had a few queries relating to the tables that have been created and populated.

1) Context Table - How is the Stable_ID generated ?
2) Stable-label Table - What do context-stable-ids refer to ?
3) Spouse Table - person1_cid, person2_cid - What do these two fields refer to ?
4) Feature Table - What does key_id, value refer to ?
5) Marginal Table - The values are already popluated in this db. Shouldn't this table get popoulated after the generative model is run ?

It would really appreciate it if you could find some time to answer our queries.

**Comment by bhancock8** [comment]
Hi @skk123123, 
These are some good questions. You're correct, the spouse tutorial included a database where preprocessing had already occurred. The good news, the new v0.9 that will be pushed in August will come with a bunch of new tutorials that are more transparent about dataset preprocessing. We're also making the entire system more modular (e.g., no db backend), so it should be much simpler to get your data into an appropriate format to work with all the snorkel tools. Stay tuned for that release!

**Comment by henryre** [comment]
Hi @skk123123, Snorkel v0.9 lets you store your data however you want, and relies on you importing your data as a DataFrame (Pandas, Spark, Dask) or a NumPy array. This sounds like it will suit your usecase much better. Take a look at our [new intro tutorial](https://www.snorkel.org/use-cases/01-spam-tutorial) for some ideas.
