### ISSUE TITLE
RandomSearch convers SerarchSpace-Parameters to Numpy Datatypes

### ISSUE THREAD

**Issue by HermannKroll** [snorkel-team/snorkel#1102]
Hi,

I'm working with Snorkel for my own research. I found some interesting issue and I'm not sure, whether this is intended or not. I  trained a descriptive model (LSTM) to extract some relations from the text, successfully. Next, I wanted to do a GridSearch to improve the performance of the network as suggested. Therefore, I used the RandomSearch object from snorkel.learning (in utils.py). Everything worked fine for me.

Then, I replaced the LSTM with an LSTM coming with GPU support (see https://github.com/sujitpal/snorkel-pytorch-lstm-gpu). The training is working, but when I try to use the RandomSearch object, it crashes. I finally  stepped into your code and found the problem:

There is type conversion from int to numpy.int64 and I think this is not intended. The following method of the RandomSearch Class (see utils.py in snorkel.learning) converts every datatype (int, float) to an numpy datatype, which finally crashes my GPU-LSTM. 

```
def search_space(self):
        return list(zip(*[self.rand_state.choice(self.parameter_dict[pn], self.n)
            for pn in self.param_names]))
```

In contradiction, the search_space method of the GridSearch object does not do a type conversion:

```
def search_space(self):
    return list(zip(*[self.rand_state.choice(self.parameter_dict[pn], self.n)
        for pn in self.param_names]))
```

I have written a short test script to verify my assumption.

```
import numpy as np

param_grid = {}
param_grid['batch_size'] = [64, 128]
param_grid['hidden_dim'] = [50, 100, 150]
param_grid['dropout'] = [0, 0.25, 0.5]

param_names = []
param_names.extend(param_grid.keys())


for pn, pv in param_grid.items():
    print('ParamGrid {} (type = {}) = {}'.format(pn, type(pv[0]), pv))
    
def search_space():
    return product(*[param_grid[pn] for pn in param_names])

rand_state = np.random.RandomState()
n = 1
def search_space_2():
    return list(zip(*[rand_state.choice(param_grid[pn], n)
            for pn in param_names]))

        
for k, param_vals in enumerate(search_space_2()):
        print('Search Space with Numpy Random State')
        for v in param_vals:
            print('{} (type = {})'.format(v, type(v)))
        print('\n')
        

param_names = param_names[0:1]
for k, param_vals in enumerate(search_space()):
        print('Search Space')
        for v in param_vals:
            print('{} (type = {})'.format(v, type(v)))
        print('\n')
```

It will print the following output:

```
You can see type int and float here
ParamGrid batch_size (type = <class 'int'>) = [64, 128]
ParamGrid hidden_dim (type = <class 'int'>) = [50, 100, 150]
ParamGrid dropout (type = <class 'int'>) = [0, 0.25, 0.5]

With the random search object => Numpy Datatypes
Search Space with Numpy Random State
128 (type = <class 'numpy.int64'>)
100 (type = <class 'numpy.int64'>)
0.5 (type = <class 'numpy.float64'>)

With the classical GridSearch  => Python Datatypes

Search Space
64 (type = <class 'int'>)
Search Space
128 (type = <class 'int'>)
```

I can fix it for me on my own, but I'm not sure, if this was intended. The issue is caused by the np.random.RandomState object. 

See:
```
print(type(param_grid[param_names[0]][0]))
print(type(rand_state.choice(param_grid[param_names[0]])))
```
Will print:
```
<class 'int'>
<class 'numpy.int64'>
```

I am using Python 3.6. If it's not intended, then I can make a pull request. 

Best Regards,
Hermann

**Comment by henryre** [comment]
Hi @HermannKroll, we've moved the information extraction version of Snorkel (v0.7) and these grid searching utilities to https://github.com/snorkel-team/snorkel-extraction. Feel free to reopen this issue (or submit your fix) there!
