### ISSUE TITLE
Training data creation on custom data

### ISSUE THREAD

**Issue by sarthak221995** [snorkel-team/snorkel#1109]
**UseCase -[Data Labelling Task] Label Employee name, organisation and the skillset from resume dataset using SNORKEL.**

Struck on candidate selection phase. Spacy NER tagger or in fact any other tagger including Stanford, NLTK etc. does not work well on Indian data. Most of them "to be candidates" are either not tagged or are wrongly mapped to other tags. Being one of the first steps (Reference - Spouse Pairs Detection) for labelling task, I am not able to proceed further. 

So first do Candidate Selection is the mandatory step and if yes, how could I go further if there is no good tagger available.

**Comment by vincentschen** [comment]
Hi @sarthak221995 — this sounds like a great application! In general, the information extraction use case (which we've moved as an end-to-end application at https://github.com/snorkel-team/snorkel-extraction) does assume some preprocessing step for candidate generation.

We do have some [prior work](https://arxiv.org/abs/1704.06360) on training data for biomedical NER; that could be a good place to start. We also have a [thread on our forum](https://spectrum.chat/snorkel/tutorials/snorkel-tutorial-for-ner~34d56436-41e6-4216-a05b-59cf391a7fb3) tracking NER tutorials in Snorkel — please feel free to contribute!

**Comment by ajratner** [comment]
Closing for now, feel free to re-open (although might be more appropriate in the snorkel-extraction repo)
