### ISSUE TITLE
Cannot perform GridSearch for GenerativeModel *with* LF dependencies

### ISSUE THREAD

**Issue by chaturv3di** [snorkel-team/snorkel#1138]
The last cell of [tutorials/workshop/part3](https://github.com/HazyResearch/snorkel/blob/master/tutorials/workshop/Workshop_3_Generative_Model_Training.ipynb) briefly talks about Structure Learning. Here's the code: 

```python
searcher = RandomSearch(GenerativeModel, param_grid, L_train, n=4, lf_propensity=False)

gen_model, run_stats = searcher.fit(L_dev, L_gold_dev, deps=deps)
```

The thing is that the method [`GridSearch.fit()`](https://github.com/HazyResearch/snorkel/blob/4506fbd74d3dd0905d4b3bd5915008f772415273/snorkel/learning/utils.py#L338) does not take `deps` as an argument. And therefore, the last statement raises an error.

So my understanding is that, *at present*:

1. If I wish to use dependencies, then I can only train a generative model with fixed hyper-parameters.
2. If I wish to use grid search, then I cannot benefit from dependencies since there is no way to pass it to the searcher.
3. This seems like an easy thing to fix; just add another argument to `fit()` and pass it to the model object created from the `self.model_class` field. The would only be a problem if the same utility does the grid search for discriminative models as well.

Is my understanding correct?

**Comment by chaturv3di** [comment]
Okay, it turns out that there is a more fundamental obstacle to using `GridSearch` with `GenerativeModel`. The `train` method of `GenerativeModel` does not recognise keyword arguments `X_dev` and `Y_dev`, which are passed through `GridSearch`'s `fit` method.

```python
searcher = RandomSearch(GenerativeModel, param_ranges, L_train, n=10, model_class_params=model_class_params)

# This statement raises errors...
gen_model, run_stats = searcher.fit(L_gold, l_gold)
```

The errors start with unexpected argument `X_dev`

```python
============================================================
[1] Testing step_size = 5.00e-03, decay = 9.50e-01, epochs = 10, reg_param = 1.00e-03, LF_acc_prior_weight_default = 1.00e+00
============================================================
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/learning/utils.py in _fit_st(self, X_valid, Y_valid, b, beta, set_unlabeled_as_neg, eval_batch_size)
    399                 model.train(*train_args, X_dev=X_valid, Y_dev=Y_valid, 
--> 400                     save_dir=self.save_dir, **hps)
    401             except:

TypeError: train() got an unexpected keyword argument 'X_dev'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-15-364716bde2d1> in <module>
----> 1 gen_model, run_stats = searcher.fit(L_gold, l_gold)

/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/learning/utils.py in fit(self, X_valid, Y_valid, b, beta, set_unlabeled_as_neg, n_threads, eval_batch_size)
    357             opt_model, run_stats = self._fit_st(X_valid, Y_valid, b=b, 
    358                 beta=beta, set_unlabeled_as_neg=set_unlabeled_as_neg,
--> 359                 eval_batch_size=eval_batch_size)
    360         return opt_model, run_stats
    361 

/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/learning/utils.py in _fit_st(self, X_valid, Y_valid, b, beta, set_unlabeled_as_neg, eval_batch_size)
    400                     save_dir=self.save_dir, **hps)
    401             except:
--> 402                 model.train(*train_args, **hps)
    403 
    404             # Test the model

/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/learning/gen_learning.py in train(self, L, deps, LF_acc_prior_weights, LF_acc_prior_weight_default, labels, label_prior_weight, init_deps, init_class_prior, epochs, step_size, decay, reg_param, reg_type, verbose, truncation, burn_in, cardinality, timer, candidate_ranges, threads)
    140         if not issubclass(element_type, np.integer):
    141             raise ValueError("""Label matrix must have int-type elements, 
--> 142                 but elements have type %s""" % element_type)
    143 
    144         # Automatically infer cardinality

ValueError: Label matrix must have int-type elements, 
                but elements have type <class 'numpy.float64'>
```

Just to confirm, the label matrix `l_gold` is of the correct type:
```python
<20x1 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>
```

It seems that the tutorials need updating.

**Comment by MaviccPRP** [comment]
I got exactly the same issue, described above. Any suggestions?

**Comment by chaturv3di** [comment]
It seems to me that this is a missing functionality in the `GridSearch` class. One could implement this by performing checks on `model_class` field of `GridSearch`, based on whether we are searching for  a discriminative model or a generative model. But that might make the code a bit clumsy, e.g. this [try-except block](https://github.com/HazyResearch/snorkel/blob/4506fbd74d3dd0905d4b3bd5915008f772415273/snorkel/learning/utils.py#L398) would have to be implemented conditionally and maybe more things after it. I wonder if one would rather implement separate grid search classes for generative and discriminative models.

There is no confirmation whether or not this is something that's going to be fixed in the upcoming `v0.9` release. Could @ajratner, @bhancock8, or @paroma please confirm?

**Comment by henryre** [comment]
Hi @chaturv3di, does passing `deps` into the `model_hyperparams` arg of `GridSearch` work for you? We're adding examples of using various hyperparameter tuning libraries for the label model in v0.9.

**Comment by chaturv3di** [comment]
@henryre, I had completely overlooked this. My bad. 

I'll verify this in my experiment and close this issue if it works (which it should). Just the tutorial notebook needs to be updated.

**Comment by bhancock8** [comment]
Closing this for now. Reopen an issue in the snorkel-extraction (https://github.com/snorkel-team/snorkel-extraction) if you still have this issue, as the GenerativeModel has been replaced with the [LabelModel](https://snorkel.readthedocs.io/en/v0.9.0/packages/_autosummary/labeling/snorkel.labeling.LabelModel.html) class in v0.9.
