### ISSUE TITLE
LabelAnnotator loads empty matrix

### ISSUE THREAD

**Issue by chaturv3di** [snorkel-team/snorkel#1139]
This is related to #867. 

When calling `load_matrix` on `LabelAnnotator`, I receive sparse matrix of type `numpy.float64`. But not always.

`L_train = labeler.load_matrix(session, split=train_split, coerce_int=True)` returns matrix of type `numpy.int64`. 

`L_gold = labeler.load_matrix(session, split=test_split, coerce_int=True)` returns the wrong type and with **zero** stored elements.

```
<20x21 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>
```

This happens even though at the time of `labeler.apply()`, both `L_train` and `L_gold` are matrices of type `int` with non-zero elements.

**Comment by paroma** [comment]
We are in the middle of a refactor which we will release later this summer that should address this issue

**Comment by chaturv3di** [comment]
Is there a fix that you can share right now to help me avoid this problem in my local installation?

**Comment by bhancock8** [comment]
Good news! Creating label matrices from labeling functions just got way easier with the v0.9 release that dropped today. You no longer need a SQLAlchemy session, for one. Check out the Getting Started tutorial (https://www.snorkel.org/get-started/) or the new Snorkel website for a demonstration of the much improved interface. If that doesn't solve your problems, feel free to post another issue.
