### ISSUE TITLE
Extracting correlations and accuracies of labeling functions

### ISSUE THREAD

**Issue by mhigginslp** [snorkel-team/snorkel#1154]
Is there a way to extract the accuracies and correlations of the labeling functions, preferably in run-time?

**Comment by vincentschen** [comment]
We're working on a re-design in which this will be readily available!

**Comment by bhancock8** [comment]
Yep! The learned weights given to the LFs when combining them are related to their accuracies, and those can be extracted from the new `LabelModel` in Snorkel v0.9 using the method [get_weights()](https://snorkel.readthedocs.io/en/v0.9.0/packages/_autosummary/labeling/snorkel.labeling.LabelModel.html#snorkel.labeling.LabelModel.get_weights). The learned correlations are not yet exposed in the current API but will be coming soon in a minor version update.

**Comment by winklerjustine** [comment]
Is there an update on this already?

**Comment by vincentschen** [comment]
Thanks for the ping @winklerjustine — the `LabelModel` now has a [`get_weights()`](https://snorkel.readthedocs.io/en/master/packages/_autosummary/labeling/snorkel.labeling.LabelModel.html#snorkel.labeling.LabelModel.get_weights) method that returns the weights used to combine LF outputs. Hope that helps!

**Comment by winklerjustine** [comment]
Thanks for the fast answer! 
Sorry, I didn't formulate my question clearly enough. Actually, I was referring to the correlations and intended to ask how I could get those.

**Comment by ajratner** [comment]
Hi @winklerjustine ,

Those are not available yet on the current master branch version, though we've published on ways to estimate them and will have them accessible in a future release.

Thanks,
Alex

**Comment by winklerjustine** [comment]
Hi @ajratner, 

That's great! Could you please point me to where I can find the formula for estimating the correlations? 

Thanks!

**Comment by vincentschen** [comment]
Hi @winklerjustine — @paroma gave a related answer on this thread: https://github.com/snorkel-team/snorkel/issues/1512#issuecomment-554506917

Hope that helps!
