### ISSUE TITLE
Unable to install Snorkel in Mac OS

### ISSUE THREAD

**Issue by agarwmae** [snorkel-team/snorkel#1226]
I am getting the below error when I am running the **conda env create --file=environment.yml** command to install Snorkel in Mac OS.

Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): | WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> bzip2[version='>=1.0.6,<2.0a0']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> libcxx[version='>=4.0.1'] -> libcxxabi==8.0.0=4
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> libffi[version='>=3.2.1,<3.3.0a0']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> pip -> setuptools -> certifi[version='>=2016.09']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> pip -> wheel
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='>=6.1,<6.2.0a0']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> sqlite[version='>=3.28.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> sqlite[version='>=3.28.0,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> tk[version='>=8.6.9,<8.7.0a0']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> python -> xz[version='>=5.2.4,<5.3.0a0']
  - matplotlib==3.0.1 -> cycler[version='>=0.10'] -> six
  - matplotlib==3.0.1 -> freetype[version='>=2.9.1,<3.0a0'] -> libpng[version='>=1.6.35,<1.7.0a0']
  - matplotlib==3.0.1 -> kiwisolver
  - matplotlib==3.0.1 -> matplotlib-base==3.0.1=py36hebca740_1001
  - matplotlib==3.0.1 -> numpy -> libblas[version='>=3.8.0,<4.0a0'] -> libcblas==3.8.0=10_mkl -> liblapack==3.8.0=10_mkl -> liblapacke==3.8.0=10_mkl -> blas=[build=mkl] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - matplotlib==3.0.1 -> numpy -> libblas[version='>=3.8.0,<4.0a0'] -> mkl[version='>=2019.0,<2020.0a0'] -> intel-openmp
  - matplotlib==3.0.1 -> numpy -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libopenblas==0.3.6=hd44dcd8_4
  - matplotlib==3.0.1 -> numpy -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> nomkl==3.0=0
  - matplotlib==3.0.1 -> numpy -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> openblas-devel==0.3.6=0
  - matplotlib==3.0.1 -> numpy -> libgfortran-ng[version='>=3.0']
  - matplotlib==3.0.1 -> numpy -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0']
  - matplotlib==3.0.1 -> numpy -> mkl_random[version='>=1.0.2,<2.0a0']
  - matplotlib==3.0.1 -> pyparsing
  - matplotlib==3.0.1 -> python-dateutil
  - matplotlib==3.0.1 -> pytz
  - matplotlib==3.0.1 -> tornado
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> libcblas==3.8.0=10_mkl -> liblapack==3.8.0=10_mkl -> liblapacke==3.8.0=10_mkl -> blas=[build=mkl] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> mkl[version='>=2019.0,<2020.0a0'] -> intel-openmp
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libopenblas==0.3.6=hd44dcd8_4
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> nomkl==3.0=0
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> openblas-devel==0.3.6=0
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> libgfortran-ng[version='>=3.0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> bzip2[version='>=1.0.6,<2.0a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> libcxx[version='>=4.0.1'] -> libcxxabi==8.0.0=4
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> libffi[version='>=3.2.1,<3.3.0a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.1,<6.2.0a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> readline[version='>=8.0,<9.0a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='>=3.28.0,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - nltk==3.2.5 -> gensim -> numpy[version='>=1.11.3,<2.0a0'] -> python[version='>=3.6,<3.7.0a0'] -> xz[version='>=5.2.4,<5.3.0a0']
  - nltk==3.2.5 -> gensim -> scipy[version='>=0.18.1']
  - nltk==3.2.5 -> gensim -> six[version='>=1.5.0']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> docutils[version='>=0.10']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> jmespath[version='>=0.7.1,<1.0.0']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> python-dateutil[version='>=2.1,<3.0.0']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> cryptography[version='>=1.3.4'] -> asn1crypto[version='>=0.21.0']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> cryptography[version='>=1.3.4'] -> cffi[version='>=1.7'] -> pycparser
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> cryptography[version='>=1.3.4'] -> cryptography-vectors=2.3.1
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> cryptography[version='>=1.3.4'] -> enum34
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> cryptography[version='>=1.3.4'] -> idna[version='>=2.1']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> cryptography[version='>=1.3.4'] -> ipaddress
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> pyopenssl[version='>=0.14']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> botocore[version='>=1.12.183,<1.13.0'] -> urllib3[version='>=1.20,<1.26'] -> pysocks[version='>=1.5.6,<2.0,!=1.5.7']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto3 -> s3transfer[version='>=0.2.0,<0.3.0'] -> futures[version='>=2.2.0,<4.0.0']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> boto[version='>=2.32']
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> bz2file
  - nltk==3.2.5 -> gensim -> smart_open[version='>=1.2.1'] -> requests
  - nltk==3.2.5 -> matplotlib -> functools32
  - nltk==3.2.5 -> matplotlib -> pyparsing
  - nltk==3.2.5 -> python-crfsuite
  - nltk==3.2.5 -> scikit-learn
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> blinker
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> entrypoints[version='>=0.3.0,<0.4.0'] -> configparser[version='>=3.5'] -> backports
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> mccabe[version='>=0.6.0,<0.7.0']
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> pycodestyle[version='>=2.5.0,<2.6.0']
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> pyflakes[version='>=2.1.0,<2.2.0']
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8 -> typing
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> flake8-import-order -> asttokens
  - nltk==3.2.5 -> twython -> requests-oauthlib[version='>=0.4.0'] -> oauthlib[version='>=0.6.2'] -> pyjwt[version='>=1.0.0'] -> pep8-naming -> flake8-polyfill[version='>=1.0.2,<2']
  - numba==0.43.1 -> funcsigs
  - numba==0.43.1 -> libcxx[version='>=4.0.1'] -> libcxxabi==8.0.0=4
  - numba==0.43.1 -> llvmlite[version='>=0.28.0,>=0.28.0,<0.29.0a0'] -> enum34
  - numba==0.43.1 -> llvmlite[version='>=0.28.0,>=0.28.0,<0.29.0a0'] -> python[version='>=3.7,<3.8.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> libcblas==3.8.0=10_mkl -> liblapack==3.8.0=10_mkl -> liblapacke==3.8.0=10_mkl -> blas=[build=mkl] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> mkl[version='>=2019.0,<2020.0a0'] -> intel-openmp
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libopenblas==0.3.6=hd44dcd8_4
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> nomkl==3.0=0
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> openblas-devel==0.3.6=0
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> libgfortran-ng[version='>=3.0']
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0']
  - numba==0.43.1 -> numpy[version='>=1.9.3,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0']
  - numba==0.43.1 -> singledispatch -> six
  - numba==0.43.1 -> tbb[version='>=2018.0.5']
  - numpy==1.16.1 -> libcxx[version='>=4.0.1']
  - numpy==1.16.1 -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - numpy==1.16.1 -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0']
  - numpy==1.16.1 -> openblas[version='>=0.3.3,<0.3.4.0a0'] -> libopenblas==0.3.3=hdc02c5d_3
  - numpy==1.16.1 -> python[version='>=3.7,<3.8.0a0']
  - pandas==0.24.2 -> libcxx[version='>=4.0.1']
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> libcblas==3.8.0=10_mkl -> liblapack==3.8.0=10_mkl -> liblapacke==3.8.0=10_mkl -> blas=[build=mkl] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> mkl[version='>=2019.0,<2020.0a0'] -> intel-openmp
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libopenblas==0.3.6=hd44dcd8_4
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> nomkl==3.0=0
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> openblas-devel==0.3.6=0
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0']
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0']
  - pandas==0.24.2 -> numpy[version='>=1.14.6,<2.0a0'] -> python[version='>=3.6,<3.7.0a0']
  - pandas==0.24.2 -> python-dateutil[version='>=2.5.*']
  - pandas==0.24.2 -> pytz
  - pytorch==1.1.0 -> cffi -> libffi[version='>=3.2.1,<3.3.0a0'] -> libcxx[version='>=4.0.1'] -> libcxxabi==8.0.0=4
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> bzip2[version='>=1.0.6,<2.0a0']
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> pip -> wheel
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='>=6.1,<6.2.0a0']
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.28.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.28.0,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - pytorch==1.1.0 -> cffi -> pycparser -> python[version='>=3.7,<3.8.0a0'] -> xz[version='>=5.2.4,<5.3.0a0']
  - pytorch==1.1.0 -> future
  - pytorch==1.1.0 -> mkl[version='>=2018'] -> intel-openmp
  - pytorch==1.1.0 -> ninja
  - pytorch==1.1.0 -> numpy[version='>=1.11'] -> libblas[version='>=3.8.0,<4.0a0'] -> libcblas==3.8.0=10_mkl -> liblapack==3.8.0=10_mkl -> liblapacke==3.8.0=10_mkl -> blas=[build=mkl] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - pytorch==1.1.0 -> numpy[version='>=1.11'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libopenblas==0.3.6=hd44dcd8_4
  - pytorch==1.1.0 -> numpy[version='>=1.11'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> nomkl==3.0=0
  - pytorch==1.1.0 -> numpy[version='>=1.11'] -> libblas[version='>=3.8.0,<4.0a0'] -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> openblas-devel==0.3.6=0
  - pytorch==1.1.0 -> numpy[version='>=1.11'] -> libgfortran-ng[version='>=3.0']
  - pytorch==1.1.0 -> numpy[version='>=1.11'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0']
  - pytorch==1.1.0 -> numpy[version='>=1.11'] -> mkl_random[version='>=1.0.2,<2.0a0']
  - scipy==1.2.1 -> openblas[version='>=0.3.3,<0.3.4.0a0']
  - scipy==1.2.1 -> python[version='>=3.6,<3.7.0a0']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> libcxx[version='>=4.0.1']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> bzip2[version='>=1.0.6,<2.0a0']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> libffi[version='>=3.2.1,<3.3.0a0']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> pip
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='>=6.1,<6.2.0a0']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.28.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> sqlite[version='>=3.28.0,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - spacy==1.9.0 -> cymem[version='>=1.30,<1.32.0'] -> python[version='>=3.7,<3.8.0a0'] -> xz[version='>=5.2.4,<5.3.0a0']
  - spacy==1.9.0 -> dill[version='>=0.2,<0.3']
  - spacy==1.9.0 -> ftfy[version='>=4.4.2,<5.0.0']
  - spacy==1.9.0 -> murmurhash[version='>=0.26,<0.27']
  - spacy==1.9.0 -> numpy[version='1.12.*,>=1.7'] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - spacy==1.9.0 -> numpy[version='1.12.*,>=1.7'] -> mkl[version='>=2018.0.0,<2019.0a0'] -> intel-openmp
  - spacy==1.9.0 -> numpy[version='1.12.*,>=1.7'] -> openblas[version='>=0.3.3,<0.3.4.0a0'] -> libopenblas==0.3.3=hdc02c5d_3
  - spacy==1.9.0 -> numpy[version='1.12.*,>=1.7'] -> openblas[version='>=0.3.3,<0.3.4.0a0'] -> nomkl==3.0=0
  - spacy==1.9.0 -> numpy[version='1.12.*,>=1.7'] -> openblas[version='>=0.3.3,<0.3.4.0a0'] -> openblas-devel==0.3.3=3
  - spacy==1.9.0 -> plac[version='>=0.9.6,<1.0.0']
  - spacy==1.9.0 -> preshed[version='>=1.0.0,<2.0.0']
  - spacy==1.9.0 -> regex[version='>=2017.4.1,<2017.12.1']
  - spacy==1.9.0 -> requests[version='>=2.11.0,<3.0.0']
  - spacy==1.9.0 -> six
  - spacy==1.9.0 -> thinc[version='>=6.5.0,<6.6.0'] -> pathlib[version='>=1.0.0,<2.0.0']
  - spacy==1.9.0 -> ujson[version='>=1.35']

**Comment by ajratner** [comment]
Hi @agarwmae sorry for the issue!  Not exactly sure what's going on here... we are a few weeks away from a big new v0.9 release where we will have overhauled all the install instructions, so it should be fixed by then!  In the mean time, perhaps someone else here has seen this issue?

**Comment by oribarel** [comment]
Hi, I had similar (but not exactly the same) issue. My solution for that was to use conda only for the installation of numpy, pandas, scipy, matplotlib , nltk, tensorflow, and pytorch. For all the rest I used pip and manually installed the different packages.

**Comment by chaturv3di** [comment]
Hi @agarwmae, +1 on Python version as pointed out by @oribarel. First create a new virtual environment with Python version `3.6.*` and not `3.7`. And then follow the installation instructions. 

Also, pay attention to package versions in `environment.yml`.

1. Stick with Scipy `1.2.1` and spaCy `1.9.0`.
2. If you wish to install TensorFlow, use version `1.12.*` (the latest `1.13` is incompatible with spaCy `1.9.0`).

**Comment by knowlsie** [comment]
On the newest branches, I'm finding this to be a problem even with 3.6. :') The requirements are actually unsatisfiable in conda right now, by the looks of things. The easiest workaround is just to install **torchtext** separately through pip; I think everything else should be doable through conda or your preferred package manager.

**Comment by bhancock8** [comment]
I have good news! With the new v0.9 release, Snorkel is WAY easier to install and much more stable. Check out the "Get Started" page (https://www.snorkel.org/get-started/) for details. It's available via conda immediately (conda install snorkel -c conda-forge) and available for pip with a full link (pip install https://github.com/snorkel-team/snorkel/releases/download/v0.9.0/snorkel-0.9.0-py3-none-any.whl). We're working with PyPI to have it available by name only (`pip install snorkel`) shortly as well. Enjoy!

**Comment by bhancock8** [comment]
And now it's up on PyPI, so `pip install snorkel` ought to do it!
