### ISSUE TITLE
Support for ordinal labels

### ISSUE THREAD

**Issue by phtully** [snorkel-team/snorkel#1280]
It's my understanding that Snorkel as currently formulated focuses primarily on problems that have binary or multi-class (categorical) labels. Some tasks, like learning to rank (LTR), can be trained instead using ordinal labels. Can Snorkel be extended so that it can generate probabilistic ordinal labels?

For example, you can imagine my targets consist of integer ranks between 1 and 5, where 5 is ranked above 4 which is ranked above 3 etc. In a simple example if I have four labeling functions, two return "5" and two return "3" for a given sample's label, I believe Snorkel would essentially guess one of either 3 OR 5. However, from the perspective of LTR, maybe you'd want Snorkel to sometimes guess 4 too.

**Comment by vincentschen** [comment]
Thanks for the input! We're considering this on our roadmap along with regression LFs and will revisit this once v0.9 is released.

**Comment by phtully** [comment]
Thanks Vincent. Any workarounds in the short-term, or do you have any insights into what the best way to do this might be given the current state of the codebase?

**Comment by vincentschen** [comment]
> Thanks Vincent. Any workarounds in the short-term, or do you have any insights into what the best way to do this might be given the current state of the codebase?

@phtully — in the short-term, it might make sense to quantize your task more heavily into categorical labels (e.g. high relevance, low relevance, irrelevant). 

We'd need larger changes to the LabelModel to support ordinal labels natively.

**Comment by phtully** [comment]
Following your advice I can confirm this approach works, but I'm sacrificing pertinent ordinality information. Now that v0.9 is out, perhaps it's worth revisiting? I can help / work on a PR if you point in the right general direction too - for example, what specific changes you had in mind for LabelModel to enable native support of ordinal labels?

**Comment by vincentschen** [comment]
Hi @phtully, this is on our roadmap, but we're open to your thoughts here!

**Comment by wazzed** [comment]
> Hi @vincentschen, currently I am working with Snorkel toward my Ph.D. research in Germany and I need this feature of "Ordinal Labeling" in Snorkel. Is there any update about it or when it can available?
