### ISSUE TITLE
How to use gpu for the parser or limit memory usage?

### ISSUE THREAD

**Issue by serendipity5497** [snorkel-team/snorkel#1300]
Hi can I limit the space used by the spacy parser or is there an argument that I can add for gpu usage

**Comment by vincentschen** [comment]
What's the error you're running into? 

We're shipping a redesigned spacy preprocessor in the upcoming v0.9 release, which might help!

**Comment by serendipity5497** [comment]
I am trying to preprocess 500k docs using the snorkel corpus parser module(spacy parser), which while running on cpu puts a time constraint. Is there any way to run it on the gpu?

**Comment by bhancock8** [comment]
With the v0.9 release today, we no longer require the use of a corpus parser or candidate extractor. I think you'll find the new modularity quite liberating. :) If you need to use spaCy as a part of preprocessing, you can now do that before you bring your data points into the Snorkel system (and apply any settings that spaCy supports), or you can use it as part of a Preprocessor that gets passed into an LFApplier. See the [spam tutorial](https://www.snorkel.org/use-cases/01-spam-tutorial) for sample usage or the documentation for the [NLPLabelingFunction](https://snorkel.readthedocs.io/en/v0.9.0/packages/_autosummary/labeling/snorkel.labeling.lf.nlp.NLPLabelingFunction.html#snorkel.labeling.lf.nlp.NLPLabelingFunction).
