### ISSUE TITLE
Is Osprey implemented in current version or in the future plan?

### ISSUE THREAD

**Issue by holdonyb** [snorkel-team/snorkel#1302]
Osprey: Weak Supervision of Imbalanced Extraction Problems without Code
https://ajratner.github.io/assets/papers/Osprey_DEEM.pdf
This paper looks very promising and convenient. Is there an implementation or there will be one?

**Comment by ajratner** [comment]
Hi @holdonyb great question!  I can't speak for the version running at Intel, but the main concept here is that we can build interfaces (e.g. excel spreadsheet-based ones like in Osprey) that sit on top of, and compile down to, Snorkel.  This is something we are indeed working on- stay tuned!

There are also a number of other pipeline innovations, somewhat specific to the Osprey setting as described, that are separate from this interface- these we will add to the list; however right now pushing on a big new overall release and refactor (v0.9) so we'll revisit after that's out in early August!

Are there any specific components / aspects of Osprey that you are particularly interested in seeing in Snorkel?  Any detail you can give is great!

**Comment by ajratner** [comment]
Closing for now, feel free to re-open!

**Comment by rjurney** [comment]
@ajratner any update on this? The balancing, interface and generative/discriminative model blending are all of interest to me as I have faced a partnership extraction task myself and this paper directly addresses the huge cost in time, software and Turks I spent gathering this business graph dataset: https://blog.datasyndrome.com/open-sourcing-relatos-business-graph-database-fca220daadd8

**Comment by rjurney** [comment]
Oh, and is the code for Osprey published somewhere? I can’t find it.

**Comment by ajratner** [comment]
Hi @rjurney unfortunately any code release up to my co-authors (at Intel)!  As for some of that gen / disc model blending, not on the immediate road map, but should be straight forward to try out if you want!

**Comment by rjurney** [comment]
Understood. Yeah, their ensemble game method is a one line definition in the paper so it seems easy enough to add to the book, just reference, paraphrase and implement an extension to the text extraction model I’m building already. Thanks!
