### ISSUE TITLE
Mutliple entities and dependencies  in one sentence

### ISSUE THREAD

**Issue by ylizi** [snorkel-team/snorkel#1331]
Hello,

I have multiple entities and dependencies in one sentence and I'm using the PretaggedCandidateExtractor. For example, I have predefined dependencies  [chemical A-disease A] and [chemical B-disease B] in one sentence. However, if I use "chemical" and "disease" as key words, the model will also add dependencies [chemical A-disease B] and [chemical B-disease A]. Is there a way to remove the extra dependencies?

I'd appreciate it very much if someone can provide suggestions.

**Comment by paroma** [comment]
The `PretaggedCandidateExtractor` currently iterates through all entities to create these pairs [here](https://github.com/HazyResearch/snorkel/blob/482695989dcfcb7062be4e507dd8022c1b5e1b8e/snorkel/candidates.py#L257).  You can edit the tagger as needed!

**Comment by henryre** [comment]
Hi @ylizi, we've moved the information extraction version of Snorkel (v0.7) to https://github.com/snorkel-team/snorkel-extraction. Feel free to reopen this issue there!
