### ISSUE TITLE
Method for printing candidates

### ISSUE THREAD

**Issue by phosseini** [snorkel-team/snorkel#1350]
I've written a method that given document and table names, prints the text of all the pairs of candidates in the document. It's helpful for me since after the candidate extraction, I want to take a look at the actual text of candidates to get a better understanding of how my pattern matchers work. I wonder if you think such a method would be useful to be added to Snorkel? If yes, I optimize my method a bit and submit a pull request.

**Comment by vincentschen** [comment]
Hi @phosseini — that sounds useful! Could you share an an example of intended usage?

**Comment by phosseini** [comment]
Here's an example, let's say there's an article in our collection with id `article-1` and we want to simply see what the extracted candidates are in `article-1` after the candidate extraction phase (with whatever method/matcher we used for candidate extraction.) I have a method called `get_candidates_text` that can be called like the following:

`get_candidates_text(tbl_name, doc_name)`

For example, like:

`get_candidates_text("my_rel", "article-1")`

Where `my_rel` is a relation defined in Snorkel using `candidate_subclass` and `article-1` is the id of an article in our input tsv file. The output is like the following:

```
[article-2] B-cell marker <-----> LH/hCG receptor-positive
[article-2] B-cell marker <-----> CD22
[article-2] B-cell marker <-----> lymphomas
[article-2] B-cell marker <-----> T-cells
[article-2] tumors <-----> B-cell marker
[article-2] tumors <-----> LH/hCG receptor-positive
[article-2] tumors <-----> immunostained-positive
.
.
.

```

Which is a list of extracted candidates.

**Comment by vincentschen** [comment]
Sounds great! Feel free to make a PR— maybe to merge into https://github.com/HazyResearch/snorkel/blob/master/snorkel/utils.py?

**Comment by phosseini** [comment]
> Sounds great! Feel free to make a PR— maybe to merge into https://github.com/HazyResearch/snorkel/blob/master/snorkel/utils.py?

Just submitted a PR, tried to make the class a bit better, any feedback would help to improve the code.

**Comment by vincentschen** [comment]
This was awesome — closing this issue, as its currently merged in the end-to-end info extraction use case at https://github.com/snorkel-team/snorkel-extraction.

Thanks @phosseini !
