### ISSUE TITLE
How to use snorkel for binary text classification task?

### ISSUE THREAD

**Issue by s2948044** [snorkel-team/snorkel#1356]
Hi, I am currently thinking of using Snorkel for a Chinese binary text classification task, where the details are as follows:

1. The background is that I have some labeled data, but only a few (<1K), so it is hard to train a good deep net on it. Thus, originally, I use a data creation tool to automatically generate artificial sentences/texts based on some fixed sentence pattern. From this I use the generated data to train a fastText (Facebook implementation) classification model.
2. Now I would like to try out Snorkel, because I have an enormous amount of unlabeled data, and from the introduction my understanding is that it can automatically label my data given that I write some LFs (is this true?). However, the tutorials I find on the project are mostly about NER tasks, so I wonder if Snorkel is appropriate for my task. If yes, is it possible to release some tutorials for the text classification task?
3. Lastly, how does the output from the generation model for every text look like, is it a single value (e.g. 0.9) for the binary case, or a vector with two entries (e.g. 0.9, 0.1)?

Thanks in advance!

**Comment by vincentschen** [comment]
Hi @s2948044 — 
1) you're exactly right, this sounds like a great use case for Snorkel!
2) You're right, the current tutorials are mostly geared towards NER — we'll have some new tutorials in v0.9 that should be very helpful. 
3) In v0.9, we support binary labels as a 1-dimensional labels _and_ categorical, probabilistic labels.

Stay tuned— I suspect that a number of new classification tutorials will be very helpful!

**Comment by bhancock8** [comment]
v0.9 landed today! Take a look at the new resources (tutorials, documentation, etc.) and you should see a good template for your problem. For example, the `spam` tutorial (https://www.snorkel.org/use-cases/01-spam-tutorial) is focused on binary text classification as well.
