### ISSUE TITLE
Problem with SnorkelSession 

### ISSUE THREAD

**Issue by ales004** [snorkel-team/snorkel#1357]
In my opinion, what is done in this file: https://github.com/HazyResearch/snorkel/blob/master/snorkel/models/__init__.py is bad practice. 

The problem I have is that when the SnorkelSession is loaded, it also creates all the necessary tables in SQL. This is done in this line:

```python

SnorkelBase.metadata.create_all(snorkel_engine)

```

If I understand correctly this basically means that if I import the SnorkelSession object, all the Tables of the database will be created automatically.

When I tried to write a test checking Snorkel functionality, this was problematic because there was no way to remove the database each time that the test is run. The only way I found is by adding this code:

```python

snorkel_db_path = Path(__file__).parent / 'snorkel-test.db'
os.environ['SNORKELDB'] = 'sqlite:///' + str(snorkel_db_path)
# this should be here because it seems that in one of the import they are initializing the tables of the database.
if os.path.exists(snorkel_db_path):
    os.remove(snorkel_db_path)
from snorkel import SnorkelSession

```
In the import part but I don't like this kind of workaround.

Wouldn't it be better to create the database lazily (the first time that the SnorkelSession class is created)?

**Comment by ales004** [comment]
I can propose another way to solve the problem. In [this line](https://github.com/HazyResearch/snorkel/blob/master/snorkel/models/meta.py#L48), instead of returning the sqlAlchemy object, we can return a wrapper object. This wrapper object would be defined like this:

```python
class SnorkelWrapperSession(SnorkelSession):
    def __init__(self, overwrite=False):
        if overwrite:
            if not snorkel_postgres and os.path.exists(snorkel_conn_string):
                os.remove(snorkel_conn_string)
                SnorkelBase.metadata.create_all(snorkel_engine)
```

**Comment by vincentschen** [comment]
Hi @ales004 — thanks for the note! Agreed — it's messy to initialize this in the global state.

We'd love to accept a PR for your fix! As an FYI— we've moved the information extraction version of Snorkel (v0.7) to https://github.com/snorkel-team/snorkel-extraction. 

Would you mind opening up a PR or issue there to track this? (Closing on this repo for now.)
