### ISSUE TITLE
How to apply labeling functions to the entire document?

### ISSUE THREAD

**Issue by bakarov** [snorkel-team/snorkel#1384]
Hi! I want to use Snorkel for the text classification task, so I am trying to write some LFs to label my documents.

As far as I understand, in my case the Candidates are the whole documents. I have written the following CandidateExtractor (as it was stated at candidates.py):

```
FullDocCandidate = candidate_subclass('FullDocCandidate', ['docCandidate'])
fullDoc = DocCandidate()
defaultMatcher = Matcher()
cand_extractor = CandidateExtractor(FullDocCandidate, [fullDoc], [defaultMatcher])
```

I have extracted the candidates in the following way:

```
docs = session.query(Document).order_by(Document.name).all()
cand_extractor.apply(set(docs))
````

I have also written a toy LF that checks whether the text contains a word from the specified list:

```
def LF_contains_words(s):
    words = ['test']
    return 1 if any(word in s for word in words) else 0
```

So my question is: how to apply this sort of LF to the document?

I have written such snippet to label the documents:

```
labeled = []
for c in session.query(FullDocCandidate).all():
    if LF_contains_words != 0:
        labeled.append(c)
print('Number labeled: {}'.format(len(labeled)))
```

However, it does not work, because the variable being passed to the LF if a FullDocCandidate. I want to extract the text of the sentences from each document, but I cannot understand how to do it.

**Comment by bakarov** [comment]
Okay, I have finally got the idea: the text is extracted from `FullDocCandidate` with `FullDocCandidate.docCandidate.get_children()`. So I guess that if I want to extract the full text, I should extract the text from each sentence in a document and merge them, like: 

```
def LF_contains_words(s):
    words = ['test']
    full_text = ' '.join([sentence.text for sentence in s.docCandidate.get_children()])
    return 1 if any(word in full_text for word in words) else 0
```
This actually works, but I am not sure whether I call the right methods. 

Could you please have a look and tell whether this is correct from the perspective of code style?

**Comment by bhancock8** [comment]
I have good news! With the big Snorkel v0.9 release that dropped today, document classification just got a lot easier! We no longer use the ORM backend (SQLAlchemy) that required making candidate subclasses, using CandidateExtractors, etc. Take a look at the new resources (tutorials, documentation, etc.) and you should see a good template for your problem. For example, the `spam` tutorial is focused on document classification as well.
