### ISSUE TITLE
Parallel Processing NotImplementedError qsize

### ISSUE THREAD

**Issue by varun-tandon** [snorkel-team/snorkel#1389]
Hi,

I'm working with a fairly large training corpus (~~40k+ research abstracts~~21660 research abstracts) and am trying to implement parallel processing for document parsing. 

I have the following code (in a Jupyter notebook): 

```
%load_ext autoreload
%autoreload 2
%matplotlib inline
import os

os.environ['SNORKELDB'] = 'postgres:///snorkel'

from snorkel import SnorkelSession
session = SnorkelSession()

import os
from snorkel.parser import TSVDocPreprocessor

doc_preprocessor = TSVDocPreprocessor('new_data/training_parsed.tsv')

from snorkel.parser.spacy_parser import Spacy
from snorkel.parser import CorpusParser

corpus_parser = CorpusParser(parser=Spacy())
%time corpus_parser.apply(doc_preprocessor, parallelism=4)
```

I added a print line to line 44 of doc_preprocessors.py to print out the document that is processed, and the processor manages to successfully process ~21660 documents, but then throws the following exception: 

```
------------------------------------------------------------------------
NotImplementedError                    Traceback (most recent call last)
<timed eval> in <module>

~/Dropbox/Laptop files/Projects/MarkerVilleBackend/snorkel/snorkel/udf.py in apply(self, xs, clear, parallelism, progress_bar, count, **kwargs)
     51             self.apply_st(xs, clear=clear, count=count, **kwargs)
     52         else:
---> 53             self.apply_mt(xs, parallelism, clear=clear, **kwargs)
     54 
     55         if self.pb is not None:

~/Dropbox/Laptop files/Projects/MarkerVilleBackend/snorkel/snorkel/udf.py in apply_mt(self, xs, parallelism, **kwargs)
     96 
     97         # Keep track of progress counts
---> 98         total_count = in_queue.qsize()
     99         count = 0
    100 

~/anaconda2/envs/snorkel/lib/python3.6/multiprocessing/queues.py in qsize(self)
    115     def qsize(self):
    116         # Raises NotImplementedError on Mac OSX because of broken sem_getvalue()
--> 117         return self._maxsize - self._sem._semlock._get_value()
    118 
    119     def empty(self):

NotImplementedError: 
```

Is there any solution to resolving this issue, or will I have to simply use the single-threaded document processor? 

It would be great if I could get parallel processing working, as single-threaded document processing is extremely slow. 

Thanks so much for the help! Please let me know if you need any further information.

**Comment by varun-tandon** [comment]
Hi, I wanted to update this issue by providing some additional information that came up.

I ran the parser again single-threaded, and realized that the total number of documents is in fact 21660, not the 40k I indicated previously. So it appears that this error is occurring on/after the last document.

**Comment by bhancock8** [comment]
Hi @varun-tandon, good question. It looks like the error you're getting is a known issue for MacOS in the multiprocessing package (see line 116 of your message posted above). As you may have seen, with the big v0.9 release today, a lot of the old parsing code specific to information extraction (including the document parsers) has been to the `snorkel-extraction repo` (https://github.com/snorkel-team/snorkel-extraction). If this continues to be a problem, feel free to repost this issue in that repository!

**Comment by varun-tandon** [comment]
Hi @bhancock8 thanks for the reply. To clarify, does this mean that v0.9 does not have any tools baked in for extraction? If I have an existing pipeline in v0.7, but want to migrate to 0.9, would I have to take my existing data and clean it to fit the expected input formats of v0.9?

Thanks for the help!

**Comment by bhancock8** [comment]
Yep! v0.9 is focused on the modeling and learning parts of the pipeline. If your problem requires creating "candidates" for extracting out of raw documents, that is something that you would do in your pipeline before the labeling stage, which is where Snorkel v0.9 begins. If you have an existing pipeline in v0.7, then you could continue to use those tools to generate candidates and then convert them into the formats expected by v0.9 for the labeling and learning.
