### ISSUE TITLE
Applying Snorkel for QnA learning?

### ISSUE THREAD

**Issue by liuqiangict** [snorkel-team/snorkel#1390]
Hi,

I'm working on some projects like QnA. 3 columns for question, answer and label. Since the label is not correct and crowd-sourcing,  also I'm going to add some LFs for more training data. I didn't find a related tutorials on this. May I ask, do you have any examples about it, thanks.

**Comment by vincentschen** [comment]
Hi @liuqiangict — thanks for sharing you projects!

A few resources that might be of interest: 
* We open-sourced our code using Snorkel to achieve state-of-the-art results on natural language understanding tasks (including QnA) — https://github.com/HazyResearch/snorkel-superglue/
* We have a [crowdsourcing tutorial](https://github.com/snorkel-team/snorkel-tutorials/tree/master/crowdsourcing) that demonstrates usage of hybrid LF + crowdsourced labels. 

I'd also encourage you to make a post on our forum in case other Snorkel users have worked on similar problems: https://spectrum.chat/snorkel

In any case, happy to dig a bit deeper if you can share specific details about your use case. Hope this helps!

**Comment by ajratner** [comment]
Hi @liuqiangict seconding @vincentschen's answer- and please let us know how your explorations go with using Snorkel for your use case!  Closing this for now, but feel free to re-open!
