### ISSUE TITLE
Snorkel tutorials missing

### ISSUE THREAD

**Issue by jennxf** [snorkel-team/snorkel#1398]
Links to the tutorials from external sites are missing.

**Comment by bhancock8** [comment]
Thanks for posting! The site is still "under construction" for the next 24 hours as we move files around to reflect the changes in v0.9. Could you also share which link you tried though so we can double check that it's working by the end of the move?

**Comment by jennxf** [comment]
Sure:
This link https://github.com/HazyResearch/snorkel/tree/master/tutorials on
the snorkel Metal tutorial page
https://github.com/HazyResearch/metal/blob/master/tutorials/Basics.ipynb is
broken.


Cheers,
Jenn

**Comment by vincentschen** [comment]
I pushed a fix via https://github.com/HazyResearch/metal/pull/205 — thanks for notifying us @jennxf!

Feel free to open additional issues if you see broken links.
