### ISSUE TITLE
ModuleNotFoundError: No module named 'snorkel.labeling'

### ISSUE THREAD

**Issue by sambuddha-roy** [snorkel-team/snorkel#1412]
## Issue description
In the tutorial section on snorkel.org ( https://www.snorkel.org/use-cases/01-spam-tutorial ) one of the steps indicated is 
`from snorkel.labeling import labeling_function`
However, that leads to the error as in the subject

## Code example/repro steps
* Installed snorkel v0.9 on Windows 10, with conda. 
* tried to import snorkel.labeling as in the tutorial, failed.

## Expected behavior
Expected behavior is as on the tutorial page.

## System info

* How you installed Snorkel (conda, pip, source): conda 
* Build command you used (if compiling from source): conda install snorkel -c conda-forge
* OS: Windows 10
* Python version: Python 3.7
* Snorkel version: v0.9
* Versions of any other relevant libraries:

**Comment by sambuddha-roy** [comment]
Upon running snorkel.__version__ I find that this is still `0.7.0-beta`. Will wait for some more time before cloning the repo.

**Comment by henryre** [comment]
Hi @sambuddha-roy, you can try specifying the version in your install command to make sure you’re running the right version of Snorkel: `conda install snorkel==0.9.0 -c conda-forge`. I can update the README to reflect this.

**Comment by allendorf** [comment]
@henryre I tried `conda install snorkel==0.9.0 -c conda-forge` and got the following error. Seems like conda doesn't have the version of pytorch required by snorkel 0.9? Is there a different version that will work and is available on conda? 

```
PackagesNotFoundError: The following packages are not available from current channels:

  - snorkel==0.9.0 -> pytorch[version='>=1.1.0,<1.2.0']

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by henryre** [comment]
Hi @allendorf, the install directions in our tutorials repo (https://github.com/snorkel-team/snorkel-tutorials#-installing-yourself-) are more complete and handle this issue. These details should be in the main README however, will add that later today.

**Comment by henryre** [comment]
The tl;dr is

```bash
conda create --yes -n snorkel
conda activate snorkel
conda install pytorch==1.1.0 -c pytorch
conda install snorkel==0.9.0 -c conda-forge
```

**Comment by henryre** [comment]
@allendorf @sambuddha-roy going to close this out since the instructions are updated (and working on our end). Feel free to reopen if you run into issues.
