### ISSUE TITLE
Make golds, preds, probs optional in Scorer.score()

### ISSUE THREAD

**Issue by vincentschen** [snorkel-team/snorkel#1417]
## Is your feature request related to a problem? Please describe.
Passing `golds`, `preds`, and `probs` are all required to use [`Scorer.score`](https://snorkel.readthedocs.io/en/v0.9.0/packages/_autosummary/analysis/snorkel.analysis.Scorer.html?highlight=scorer#snorkel.analysis.Scorer.score). 
Often, `preds` and `probs` are not both available, and requires additional usage of a [`util`](https://snorkel.readthedocs.io/en/v0.9.0/packages/utils.html) function — AKA not the best interface!

## Describe the solution you'd like
Make certain fields (`preds` / `probs`) optional in `Scorer.score`, depending on usage.

**Comment by bhancock8** [comment]
This should actually be a pretty easy fix. Scorer.score() calls metric_score() which can be passed any combination of golds, preds, and probs and it'll complain with an error if the metric you requested didn't get all of the inputs it needs to compute. So I think all we need to do here is update the signature to let all three of those be optional.
