### ISSUE TITLE
cannot import name 'to_int_label_array'

### ISSUE THREAD

**Issue by swainsubrat** [snorkel-team/snorkel#1419]
## Issue description
from snorkel. labeling import labeling_function was not working. I saw the fix for it. Then I install all the requirements. But can't get it right.

## Code example/repro steps
#defining labeling functions
from snorkel.labeling import labeling_function

@labeling_function
def lf_isRising(a):
    """
    args:
        a: A sub-sequence
    """
    n = np.random.randn(i, sub_seq_length - i)
    n1 = np.random.randn(i, sub_seq_length - i)
    m = a[i] < a[i + n]
    m = m and a[i + n] < a[i + n + n1 % sub_seq_length]
    
    return SELL if m else 0

giving error:

ImportError                               Traceback (most recent call last)
<ipython-input-6-dca8312aae09> in <module>()
      8 
      9 #defining labeling functions
---> 10 from snorkel.labeling import labeling_function
     11 
     12 @labeling_function

~\Anaconda3\lib\site-packages\snorkel\labeling\__init__.py in <module>()
      1 """Programmatic data set labeling: LF creation, models, and analysis utilities."""
      2 
----> 3 from .analysis import LFAnalysis  # noqa: F401
      4 from .apply.core import LFApplier  # noqa: F401
      5 from .apply.pandas import PandasLFApplier  # noqa: F401

~\Anaconda3\lib\site-packages\snorkel\labeling\analysis.py in <module>()
      8 from sklearn.metrics import confusion_matrix
      9 
---> 10 from snorkel.utils import to_int_label_array
     11 
     12 from .lf import LabelingFunction

ImportError: cannot import name 'to_int_label_array'
Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## Expected behavior
It should work fine as per the documentation.

## Screenshots
No screenshots of code!

## System info

* How you installed Snorkel (conda, pip, source): Conda
* Build command you used (if compiling from source): 
* OS: Windows 10
* Python version:3.7
* Snorkel version:0.9
* Versions of any other relevant libraries:

**Comment by vincentschen** [comment]
Hi @swainsubrat — sorry about the installation issues. I ran the following on Ubuntu 16.04 in a new conda environment and it seemed to run without error:
```
➜  ~ conda create --name snorkel python=3.7
➜  ~ conda activate snorkel
(snorkel) ➜  ~ conda install snorkel -c conda-forge
(snorkel) ➜  ~ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from snorkel.labeling import labeling_function
>>> from snorkel.utils import to_int_label_array
```

Note — I didn't need to explicitly install any requirements after the `conda install snorkel -c conda-forge` step.

A few questions: 
Which python environment are you using after activating the conda environment?
```
(snorkel) ➜  ~ which python
/home/ubuntu/anaconda3/envs/snorkel/bin/python
```

Where is your `snorkel` installed?
```
>>> import snorkel
>>> snorkel.__file__
'/home/ubuntu/anaconda3/envs/snorkel/lib/python3.7/site-packages/snorkel/__init__.py'
```

Are you using the Linux subsystem in windows?

**Comment by swainsubrat** [comment]
Windows.

**Comment by vincentschen** [comment]
@swainsubrat — would you mind pasting where the above commands for `python`/`snorkel` point?

Alternatively, you could try running on Docker as suggested in the [README](https://github.com/snorkel-team/snorkel/blob/master/README.md#installation) for Windows users: https://github.com/snorkel-team/snorkel-tutorials/blob/master/Dockerfile

**Comment by SoundNandu** [comment]
ImportError: cannot import name 'SnorkelSession' from 'snorkel' (/anaconda3/envs/rti/lib/python3.7/site-packages/snorkel/__init__.py)

**Comment by SoundNandu** [comment]
facing this issue Can anyone help me ImportError: cannot import name 'SnorkelSession' from 'snorkel' (/anaconda3/envs/rti/lib/python3.7/site-packages/snorkel/__init__.py)

**Comment by SoundNandu** [comment]
Facing this issue  -- 
ImportError: cannot import name 'SnorkelSession' from 'snorkel' (/anaconda3/envs/rti/lib/python3.7/site-packages/snorkel/__init__.py)

**Comment by SoundNandu** [comment]
ImportError: cannot import name 'SnorkelSession' from 'snorkel' (/anaconda3/envs/rti/lib/python3.7/site-packages/snorkel/__init__.py)

**Comment by AanchalA** [comment]
> 
> 
> Facing this issue --
> ImportError: cannot import name 'SnorkelSession' from 'snorkel' (/anaconda3/envs/rti/lib/python3.7/site-packages/snorkel/**init**.py)

Did you find a solution? I am facing the same issue
