### ISSUE TITLE
Bug? single labeling function ignored

### ISSUE THREAD

**Issue by orenbookarang** [snorkel-team/snorkel#1426]
## Issue description

I have a single LF. It seems to operate correctly, yet the labeling ignores it.

## Code example/repro steps

[Was Filmed - With Snorkel - 23 Aug 2019(1).pdf](https://github.com/snorkel-team/snorkel/files/3533889/Was.Filmed.-.With.Snorkel.-.23.Aug.2019.1.pdf)

## Expected behavior
Behaves somewhat like the single LF. Not always -1.

## Screenshots
See attached PDF (notebook)

## System info

* How you installed Snorkel (conda, pip, source):
* Build command you used (if compiling from source):
* OS: Darwin Black-Box.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64
* Python version: Python 3.6.4
* Snorkel version: snorkel            0.9.0
* Versions of any other relevant libraries:

**Comment by orenbookarang** [comment]
By now I have discovered predict_proba, but also there it returns always [0.5, 0.5].

The next progress I had was that I've found that if my LF(s) return 0 instead of -1 in the "unknown" case, I do get interesting and relevant probabilities (not just 0.5).

Still will be happy for clarification/help or potential improvement as to make it better self explanatory.

**Comment by paroma** [comment]
The LabelModel requires at least 3 labeling functions (LFs) as input. This ensures the model has enough overlaps and conflicts to learn the parameters associated with LFs. With a single labeling function, the label model cannot learn these parameters and the outputs are therefor invalid. More details on the how the LabelModel functions [here](https://arxiv.org/abs/1810.02840)

Tracking the issue with *multiple LFs* still causing equal probabilities given the output is either an abstain or class 1 for a datapoint in #1422
