### ISSUE TITLE
End model seems to always do better when assuming a 50/50 class balancec

### ISSUE THREAD

**Issue by astarostap** [snorkel-team/snorkel#1432]
Whenever I add a class balance a priori for training Snorkel, it hurts the end model performance (I'm using logistic regression). Not sure if other people have seen this behavior as well.

**Comment by ajratner** [comment]
Hi @astarostap I'm going to close this for now as it's not detailed or specific enough for us to address as an issue, but feel free to bring up on the forums, or submit some kind of minimal example that we could look at and debug!
