### ISSUE TITLE
Supporting "default" class

### ISSUE THREAD

**Issue by astarostap** [snorkel-team/snorkel#1433]
Say you have a binary classification task. I've seen many use-cases in which the model should predict the negative by default unless an example hits a bunch of positive LFs.

However, if you only have positive LFs, then the Snorkel model seems to always predict positive.

Have others run into this? Am I missing something?

One potential solution would be to add an LF for the default class that votes True for all examples so as to default the predictions towards the default class.

**Comment by ajratner** [comment]
Which model are you talking about? 

If the `LabelModel`: there is a class balance that can be set, and also a default "tie breaker" setting to specify which way to break ties (e.g. if all the LFs abstain) in the `Scorer` class; please see the API documentation for details.

If the end model: then yes, different approaches need to be taken to handle labeled data that is only e.g. positive or unlabeled (which is often referred to as the "PU learning" setting).

Either way, more detail would help here!
