### ISSUE TITLE
negative predictions for data point with positive labels

### ISSUE THREAD

**Issue by pengdumle** [snorkel-team/snorkel#1437]
Hi,
I am using snorkel for a search result quality prediction project.
I have quite a few cases where the predictions do not quite make sense to me.
There are false negative results where the predictions are 0 (negative), but if you look at the labels assigned by each labeling functions, they are either 1(positive) or -1(abstain). There are nearly no 0(negative) at all.
Could anyone help clarify this for me please?
Thanks,
Peng

**Comment by paroma** [comment]
Can you share the L matrix and details about how you're training the LabelModel? You can also take a look at [this issue](https://github.com/snorkel-team/snorkel/issues/1422#issuecomment-523593367) for details on how ties are broken, which could be causing this behavior here

**Comment by pengdumle** [comment]
Sure.
Here are the L matrix and predictions:
L_test[:20]
array([[-1, -1, -1, -1, -1, -1, -1,  0,  0,  1, -1,  1,  1,  1,  1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1,  0,  0,  1, -1,  1,  1,  1,  1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1,  0,  0,  1, -1,  1,  1,  1,  1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1,
        -1, -1,  0, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  0,  0, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1,  1,  1,  0, -1,  1,  1,  1,  1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  0,  0,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  1,  0,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
         1,  1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  1,  0,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
         1,  1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  1,  0,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
         1,  1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
         1,  1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1,  1,  1,  1,  0,  0,  0, -1,  0,  0,  0,  0, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1,  1,  1,  1,  0,  0,  0, -1,  0,  0,  0,  0, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1,
        -1, -1,  1, -1, -1, -1, -1, -1, -1, -1]])
L_test_prediction[:20]
array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])
If you look at the 9th and 10th data point(starting from 1), you will see that for the 9th, there is only one negative with a few positives for the 10th, all of them are positive. But still, the predictions are 0 for these two.
for tie broken, I didn't input that parameter. So it should be the default one.
Thanks,
> Can you share the L matrix and details about how you're training the LabelModel? You can also take a look at [this issue](https://github.com/snorkel-team/snorkel/issues/1422#issuecomment-523593367) for details on how ties are broken, which could be causing this behavior here

**Comment by ajratner** [comment]
From taking a glance- it's quite possible that the model is converging to the wrong solution (in general, there's a symmetry that needs to be broken one way or the other), where it's assuming many of the LFs are worse than random.

It's a bit hard for us to tell and debug without having access to your label matrix.  Either way, we will be pushing out new versions of the label model that will hopefully introduce better defaults to help avoid and debug bad model estimation solutions!

**Comment by pengdumle** [comment]
Hi,
Thank you for the reply.
Here is the statistics for my labeling functions.

j | Polarity | Coverage | Overlaps | Conflicts | Correct | Incorrect | Emp. Acc.
0 | [0, 1] | 0.383162 | 0.383162 | 0.151095 | 2661 | 907 | 0.745796
1 | [0, 1] | 0.383162 | 0.383162 | 0.151095 | 2246 | 1322 | 0.629484
2 | [0, 1] | 0.383162 | 0.383162 | 0.151095 | 2181 | 1387 | 0.611267
3 | [1] | 0.170103 | 0.170103 | 0.040271 | 1319 | 265 | 0.832702
4 | [0, 1] | 0.383162 | 0.383162 | 0.151095 | 2875 | 693 | 0.805774
5 | [0, 1] | 0.377685 | 0.377685 | 0.146263 | 2752 | 765 | 0.782485
6 | [0, 1] | 0.383162 | 0.383162 | 0.151095 | 2683 | 885 | 0.751962
7 | [0, 1] | 0.342461 | 0.342461 | 0.143471 | 2153 | 1036 | 0.675133
8 | [0, 1] | 0.342461 | 0.342461 | 0.143471 | 2138 | 1051 | 0.670430
9 | [0, 1] | 0.342461 | 0.342461 | 0.143471 | 2271 | 918 | 0.712135
10 | [1] | 0.136705 | 0.136705 | 0.035009 | 1080 | 193 | 0.848390
11 | [0, 1] | 0.342461 | 0.342461 | 0.143471 | 2457 | 732 | 0.770461
12 | [0, 1] | 0.342461 | 0.342461 | 0.143471 | 2435 | 754 | 0.763562
13 | [0, 1] | 0.553909 | 0.553909 | 0.259021 | 3613 | 1545 | 0.700465
14 | [0, 1] | 0.342461 | 0.342461 | 0.143471 | 2401 | 788 | 0.752901
15 | [0, 1] | 0.031894 | 0.031894 | 0.006336 | 215 | 82 | 0.723906
16 | [0, 1] | 0.031894 | 0.031894 | 0.006336 | 220 | 77 | 0.740741
17 | [0, 1] | 0.031894 | 0.031894 | 0.006336 | 217 | 80 | 0.730640
18 | [0, 1] | 0.214240 | 0.214240 | 0.117912 | 1109 | 886 | 0.555890
19 | [0, 1] | 0.018149 | 0.018149 | 0.007410 | 95 | 74 | 0.562130
20 | [0, 1] | 0.018149 | 0.018149 | 0.007410 | 99 | 70 | 0.585799
21 | [0, 1] | 0.018149 | 0.018149 | 0.007410 | 56 | 113 | 0.331361
22 | [0, 1] | 0.018149 | 0.018149 | 0.007410 | 95 | 74 | 0.562130
23 | [0, 1] | 0.018149 | 0.018149 | 0.007410 | 91 | 78 | 0.538462
24 | [0, 1] | 0.018149 | 0.018149 | 0.007410 | 95 | 74 | 0.562130
25 | [0, 1] | 0.018149 | 0.018149 | 0.007410 | 92 | 77 | 0.544379

As you can see, there are 26 labeling functions with various coverage and accuracy.
Could you have a little more insight after seeing this? 
Or do you have some suggestions for me to debug?
Thanks,
Peng

**Comment by pengdumle** [comment]
Hi, I have a quick follow up, I found out that using the majority voter model, I could get a much higher accuracy, around 80% rather than the current 50-60%. Thanks:-)

**Comment by ajratner** [comment]
Hi @pengdumle thanks for the details!  Just to clarify: are you able to share your `L_train` matrix?  If so, I'll try to see if I can re-create (and debug) this behavior

**Comment by pengdumle** [comment]
Oh, I thought what I provided above was what you wanted.
The ltrain and ltrain_prediction files are attached.
[ltrain_prediction.txt](https://github.com/snorkel-team/snorkel/files/3572560/ltrain_prediction.txt)
[ltrain.txt](https://github.com/snorkel-team/snorkel/files/3572562/ltrain.txt)


I have added some more labeling functions, but the pattern are not changed. Still we have similar behavior. Thanks,
Peng

**Comment by ajratner** [comment]
@pengdumle I believe I’ve isolated the (or at least one) issue- it’s specifically around modeling conditional abstain probabilities in the very sparse (ie many abstains) setting using the new label model we just put in.  I should have a fix later this week if I’m correct- either way will post an update then and thanks for your patience in trying out our newest stuff!! :)

**Comment by pengdumle** [comment]
Thank you!
Peng

**Comment by pengdumle** [comment]
@ajratner 
Hi, according what I saw that "LabelModel parameter clamping fix (fixes issue 1422) #1444
 Open
4 of 4 tasks complete ". Does it mean that this problem has been solved?
How do I get the latest version? Thanks,

**Comment by ajratner** [comment]
Hi @pengdumle ,

It will be merged into master and added as a patch to the default pip version today!  I will also take a look at your label matrix to see if that fixes your issue.  If you're able to also send me the test label matrix & test gold labels (that you used to compute the above scores) I can check those as well

Thanks,
Alex

**Comment by pengdumle** [comment]
Hi @ajratner ,
The L test matrix and the predictions are attached.
[ltest.txt](https://github.com/snorkel-team/snorkel/files/3579997/ltest.txt)
[ltest_prediction.txt](https://github.com/snorkel-team/snorkel/files/3579998/ltest_prediction.txt)

Thank you!
Peng

**Comment by ajratner** [comment]
@pengdumle thanks!  Are you able to share the test labels you were using to compute the scores you were reporting above?

**Comment by pengdumle** [comment]
Yep,
The golden labels are attached.
[train_golden.txt](https://github.com/snorkel-team/snorkel/files/3580024/train_golden.txt)
[test_golden.txt](https://github.com/snorkel-team/snorkel/files/3580026/test_golden.txt)

Thanks!

**Comment by ajratner** [comment]
Hi @pengdumle - two PRs are now pushed which correct small things in the `LabelModel`, and which should correct the particularly odd cases you observed and pointed out above!  I did a spot check on your data to confirm- thanks again for sharing!

However, I wouldn't yet say that your setting is necessarily fixed- the performance is still below where I'd think it should be.  In particular, you seem to have two groups of LFs that conflict with each other and which this configuration of the `LabelModel` is having difficulty resolving.  There are many things to do to handle cases like these, but they may be out of scope for a Github issue where I don't have access to the actual data or problem context.  Either way, I'll take another look soon- and feel free to close or keep open in the mean time!

**Comment by pengdumle** [comment]
Hi @ajratner 
Thank you for updating the code.
I just reinstalled snorkel as instructed in https://github.com/snorkel-team/snorkel, and still observed high error rate.
Would you please tell me what labeling functions are having conflicts with each other? So that I can have a deeper look on my side. Thanks,
Peng

**Comment by ajratner** [comment]
Hi @pengdumle,

Sorry for the delayed response here!  As best as I can currently assess via quick triage, the issue here is no longer a specific bug, but some complexity of your setting.  We have done a lot of work on the academic end studying more complex settings, and models to handle them---for example, labeling functions with complex correlation structures, or feature-conditional accuracies---and will continue to release incrementally more advanced versions of the `LabelModel` based on this research (including one coming soon in the next minor version release!).  One of these models may help here!

Unfortunately, however, we do not currently have the resources to do custom model configuration work for open source users.  So I am closing this issue for now, but some potential next steps:
- If you find specific behavior again that looks like a clear bug, please report this as an issue and we will look into (as we did with the two other recent patches)
- Keep your eyes out for the new `LabelModel` versions, and see if these help
- Feel free to open a discussion in the Spectrum forums

Thanks!
Alex
