### ISSUE TITLE
Logging functions do not get called

### ISSUE THREAD

**Issue by Peter-UCL** [snorkel-team/snorkel#1439]
## Issue description

When logging is enabled, and the log_writer is json, nothing outputs to the log file.
Specifically, in the `snorkel/classification/training/loggers/log_writer.py` file, the `write_log` function never gets called anywhere in the code base.

I can directly call this function after training like so:
```
trainer.log_writer.write_log("output_log.json")
```
Which outputs the metric dict at the expected location.

But I feel that this should be done automatically after training (called in the `snorkel/classification/training/trainer.py` file) if logging is enabled.

## Code example/repro steps

Here is my trainer config:
```
trainer_config = {
    "progress_bar": True,              
    "n_epochs": 2, 
    "lr": 0.02, 
    "logging": True, 
    "log_writer": "json",
    "checkpointing": True,
}
```

## Expected behavior
It should output the training & validation metrics to a .json file in the "logs" folder.

**Comment by bhancock8** [comment]
Thanks for posting an issue about this! You're right---this is unexpected behavior. I'll take a look.
