### ISSUE TITLE
If I want to understand the underlying algorithm of the Generative Model in depth, what reference materials do I need to see?

### ISSUE THREAD

**Issue by anjubaoGDUT** [snorkel-team/snorkel#1455]
I have read some papers about Snorkel, but I am not clear about the underlying algorithms of the Generative Model. Is there any reference to the underlying algorithm data or related blogs? It is best to clearly express the mathematical derivation process of the Generative Model.

**Comment by ajratner** [comment]
Hi @anjubaoGDUT you can check out the AAAI'19 and NeurIPS'16 papers on the [Snorkel website](https://www.snorkel.org/resources/)!
