### ISSUE TITLE
X-post from transformers

### ISSUE THREAD

**Issue by Peter-Devine** [snorkel-team/snorkel#1474]
## Issue description

Description of the problem: https://github.com/huggingface/transformers/issues/1367

Cross-post from transformers, but my snorkel model will only result in good training using an old version of Huggingface's BertModel, and newer versions never converge. Any intuition as to why this would be?

Thanks

**Comment by vincentschen** [comment]
Hi @Peter-Devine — great to hear that you're using Snorkel with the transformers repo!

It sounds like this issue stems from the transformers repo; let's continue to track this in https://github.com/huggingface/transformers/issues/1367, like you said! If you do encounter any issues with the new transformer models related to the Snorkel API, please re-open an issue!
