### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.1.0.post2

### ISSUE THREAD

**Issue by rjurney** [snorkel-team/snorkel#1475]
## Issue description

Snorkel requires a package version of torch that does not exist on PyPi.

## Code example/repro steps

pip install snorkel

## Expected behavior

Snorkel installed

## System info

* How you installed Snorkel (conda, pip, source): pip
* Build command you used (if compiling from source): 

```bash
pip-compile --output-file requirements.txt requirements.in
pip install -r requirements.txt 
```

* OS: OS X, Linux
* Python version: 3.7.4
* Snorkel version: 0.9.1
* Versions of any other relevant libraries:

**Comment by rjurney** [comment]
For more information, see https://github.com/pytorch/pytorch/issues/10443

**Comment by henryre** [comment]
Hi @rjurney, thanks for posting and digging around on this! As far as upgrading to PyTorch 1.2: there are some breaking changes, and so we're planning to make the next version (likely v0.10.0) compatible with PyTorch 1.2. The staged PR (needs an update) is #1395.

Now for install issues: I wasn't able to repro any issue with `pip install snorkel` on Ubuntu or OSX. I tried out `pip-tools` for the first time (just using `snorkel==0.9.1` in `requirements.in`), and here's what I got:

* On Ubuntu, the resolver gave `torch==1.1.0` in `requirements.txt` and had no issue installing
* On OSX, the resolver gave `torch==1.1.0.post2` in `requirements.txt` and had no issue installing
* On Ubuntu, `pip install torch==1.1.0.post2` fails as you pointed to
* Running `pip-compile -P snorkel==0.9.1 -P torch==1.1.0` on any platform gave `torch==1.1.0` in `requirements.txt` and had no issue installing

Will one of those combos will work for you before we push the PyTorch 1.2 upgrade?

**Comment by rjurney** [comment]
Thanks for checking this out. Interesting. I’m using Anaconda Python on Ubuntu and OS X, and when I look at the list of artifacts and there is a 1.1.0.post2 so... I’m confused. I’ve had another issue like this with Anaconda pip recently. Is it possible for you to reproduce with Anaconda?

**Comment by henryre** [comment]
Hm ok you're activating a new Anaconda environment, installing pip-tools, then using that to install Snorkel? And is there any chance you generated a `requirements.txt` on OSX then tried installing with that on Ubuntu?

In the meantime, will using `pip-compile -P snorkel==0.9.1 -P torch==1.1.0` work?

**Comment by rjurney** [comment]
@henryre Ok, yeah I think I did generate on Linux and then install in OS X. So that means I can only check in my *requirements.in* and not my *requirements.txt* and then I'll have to generate it each install. That makes sense. 

https://github.com/jazzband/pip-tools/issues/585 explains things well.

**Comment by rjurney** [comment]
@henryre So now I'm running into problems with libraries like *fast-bert* require `torch>=1.2.0` and snorkel requires less than this. I understand this is not strictly speaking a Snorkel problem, but wanted to describe my use case :)

**Comment by henryre** [comment]
@rjurney got it. I expect more and more of these to pop up, and our next release will definitely be on PyTorch 1.2!

**Comment by mrbeann** [comment]
> @rjurney got it. I expect more and more of these to pop up, and our next release will definitely be on PyTorch 1.2!

When will this release come out? It's there any timeline?
