### ISSUE TITLE
Mechanism to attribute importance priors/weights to LFs

### ISSUE THREAD

**Issue by cdeepakroy** [snorkel-team/snorkel#1483]
## Is your feature request related to a problem? Please describe.

I am working on a text classification problem where in I designed 14 weakly supervised labeling functions (LF):
* 6 are derived from knowledge base 1 (kb1), 
* 6 are derived from knowledge base 2 (kb2)
* 2 are derived based on matches to a regex

I know for a fact that kb2 is much more reliable than kb1 but has less coverage. Also the regex based LF has much much less coverage than the knowledge base LFs but I know that it is very precise when there is a regex match (i.e. for the data samples it covers).

In my experiments so far, the LabelModel seems to give more weightage to LFs with high coverage. For example, I found quite a few cases where all the knowledge based LFs abstained but the regex based LF gave a +ve class label but the LabelModel ended up giving a low probability to these samples which when binarized got assigned to the -ve class. 

## Describe the solution you'd like

For the aforementioned scenarios, it will be useful to have a mechanism to provide importance priors for each LF. More generally, it might be useful to automatically infer these priors based on the performance of these LFs on a dev set that the user can provide.

## Describe alternatives you've considered

A simple hacky way is to replicate the LFs that are desired to have higher importance. But I feel this might break with the upcoming version of the label model that tries to automatically learn the dependencies between the LFs based on inverse covariance matrix and robust PCA approach.

I have tried providing the `prec_init` parameter to the `LabelModel.fit()` in the form of an array containing the precision for each LF in the label matrix, but that resulted in an error (see discussion below)

https://spectrum.chat/snorkel/help/is-it-possible-to-assign-importance-reliability-weights-to-labeling-functions~07cb5873-b72a-4501-be7c-23489966740a

I have reported the error in issue #1484

**Comment by eggie5** [comment]
+1 

Yes I have too committed this hack of duplicating LFs which require more weight (authority).

**Comment by ajratner** [comment]
Hi @cdeepakroy apologies for the delay in responding here!

First of all, I re-opened #1484 regarding the bug with setting a prior (the intended functionality, which must have been broken by some recent change, is to use centered L2 reg. to enforce a prior on the LF accuracies).  Hopefully someone can get to this soon.

Second, the recent changes in v0.9.3 might help with your label model performance?

Finally, I will note that you appear to have highly correlated LFs (two groups of six each that derive from the same KB), which is likely the source of some issues; this may be handled by structure learning approaches (such as those we've recently worked on, which are not yet, but eventually will be, in master), or in the short term you could consider reducing the number of particularly overlapping / correlated LFs per KB?
