### ISSUE TITLE
Persist branches for stable releases

### ISSUE THREAD

**Issue by chaturv3di** [snorkel-team/snorkel#1503]
For my specific use-case, I'd like to `git clone` the repo and build it locally. For this purpose, it would be immensely helpful if you could persist the (latest) stable release branches.

If you were developing as per the git-flow workflow, then `master` would be the latest stable release and all the nightly-builds could go in the `develop` branch.

I _could_ clone the entire repo and checkout the stable version based on tags, but I guess persisting those branches makes better sense. 

Your thoughts?

**Comment by henryre** [comment]
Hi @chaturv3di, thanks for the question! We've adopted a source control workflow which works well for open-source projects that use continuous integration and is based on [Github Flow](https://guides.github.com/introduction/flow/). As you pointed out, we use tags to mark stable releases. If your goal is to not checkout the full repo history, you can use the `--branch` argument for `git clone`, which works with tags as well. Closing for now, feel free to reopen if you have more questions.
