### ISSUE TITLE
Using labeling function for producing labels of numerical data. 

### ISSUE THREAD

**Issue by jennakwon06** [snorkel-team/snorkel#1505]
I was wondering if Snorkle could be used for labeling numerical data (specifically what I have is time-series). 

For example, I have a Numpy array: [100, 100, 20, 20, 20, 90, 100, 100, 100, 100], representing 10 values emitted from 10 different times. 

My labeling function would be: "If value is < 30 for more than or equal to 3 consecutive times, then label the times as 0"

The output I am looking for (or anything I can use to translate to the below) would be,
[0, 1] : 1
[2, 3, 4] : 0
[5, 6, 7, 8, 9]: 1 

Thanks!

Best,
Jenna

**Comment by paroma** [comment]
You can use Snorkel over numerical data - we have an example in [this image-based tutorial](https://www.snorkel.org/use-cases/visual-relation-tutorial) that uses features of the bounding boxes of objects in the images. For time series data specifically, we published a paper in [NeurIPS '19](https://arxiv.org/abs/1910.09505) that describes a new generative model that can handle multi resolution LFs.

For the use case in the description, you can write labeling functions that operate over the particular datapoint and its neighboring datapoints to assign a label.Y our datapoints could have fields that refer to the previous and next values in the data, which you can access from the LF:
```python
x.val = 3
x.prev_val = 2 # or None
x.next_val = 4 #or None
```

**Comment by ajratner** [comment]
Closing for now- feel free to re-open!
