### ISSUE TITLE
Compile list of weak supervision approaches for documentation

### ISSUE THREAD

**Issue by rjurney** [snorkel-team/snorkel#1507]
Problem: I’m having to survey the Snorkel tutorials, blog posts and literature to find approaches to weak supervision to try.

Solution: compile categories of techniques in a single wiki page or post

## Describe alternatives you've considered
Currently you read through a bunch of stuff to come up with ideas. A single place listing categories of techniques would be more efficient.

## Additional context
I’m working on this as part of my book so I can contribute, but mostly I just know what has appeared in the tutorials and papers. The snorkel team has had much experience working with industry so if I create something it would be great if you could add to it.

**Comment by vincentschen** [comment]
Hi @rjurney — this is a great idea. 

We had a start at this on the resources page of our website: https://www.snorkel.org/resources/ — let us know if there's anything that you'd like to add or modify!

**Comment by rjurney** [comment]
@vincentschen thanks, the list of papers is great. I’ve been running across them and expanding my list organically and it is great to have them in one place.

This is not what I’m describing, however. I’m talking about surveying those papers and creating a LF guide of the various types. One type would be keyword search, for example, with an example keyword search LF. Another type would be using an external model, for example TextBlob. They could be organized by data type and strategy.

Make sense?

**Comment by ajratner** [comment]
@rjurney makes a lot of sense and this seems like a very helpful resource to have!  We've done partial forms/versions of this in various papers / blog posts / slide decks floating around, but having one reference page (could even grow to include other weak supervision types / strategies used out in the wild that could be supported in Snorkel) would be very cool!!

**Comment by rjurney** [comment]
@ajratner Ok, I'm working on this right now. Can you open the ticket? I should have something in a week or two. Is it possible to submit a pull request to the website Github repo or is there a particular format I should use for your CMS?
