### ISSUE TITLE
cannot import name 'load_spam_dataset'

### ISSUE THREAD

**Issue by MehrdadFarokhnejad** [snorkel-team/snorkel#1508]
## Issue description

I installed Snorkel 0.9.2 ( pip install snorkel).

also, imported snorkel in my code, however, I faced this error when I want to load data. How can I solve it?

import snorkel 
from snorkel.labeling import labeling_function
from utils import load_spam_dataset

ImportError                               Traceback (most recent call last)
<ipython-input-6-e910dfd303ce> in <module>
----> 1 from utils import load_spam_dataset

ImportError: cannot import name 'load_spam_datase

Thanks in advance!

**Comment by vincentschen** [comment]
It looks like you're trying to access one of the utilities in our tutorials: https://github.com/snorkel-team/snorkel-tutorials/blob/master/spam/utils.py#L16

Try cloning this repository for the relevant resource! https://github.com/snorkel-team/snorkel-tutorials
