### ISSUE TITLE
Find dependent pairs of labeling functions

### ISSUE THREAD

**Issue by winklerjustine** [snorkel-team/snorkel#1512]
Hi, 

How can I find all pairs (or sets of 3, ..., n) of LFs that are dependent according to what the generative model has learned? Alternatively, is there a way to find the correlations of LFs?

Thanks in advance!

**Comment by paroma** [comment]
We published a few papers on how to learn dependencies among LFs ([ICML '17](https://arxiv.org/abs/1703.00854) and [ICML '19](https://arxiv.org/pdf/1903.05844.pdf)) and have a prototype of the algorithm over synthetic data [here](https://github.com/HazyResearch/dependency_model/blob/master/Learning%20Dependencies.ipynb).

**Comment by winklerjustine** [comment]
Hi @paroma,
Unfortunately, when clicking on the last link to the algorithm over synthetic data, I get a 404 error. :/
Could you please tell me where I can find that algorithm? Sounds like exactly what I need. Thank you!

**Comment by paroma** [comment]
Sorry about that! Fixed the link above - here's the [notebook](https://github.com/HazyResearch/dependency_model/blob/main/Learning%20Dependencies.ipynb)
