### ISSUE TITLE
Label model implementation of Snorkel 0.9.1

### ISSUE THREAD

**Issue by brijendra2496** [snorkel-team/snorkel#1513]
Hi all,

I am looking at Label Model of Snorkel version 0.9.1. But I am not getting from which research paper of Snorkel, Label Model is implemented in Snorkel version 0.9.1. 
I really want to know how Label Model is implemented and from which research paper the concepts are integrated in Label Model of Snorkel version 0.9.1 

Thanks in Advance

**Comment by ajratner** [comment]
Hi @brijendra2496 you can check out the API docs for many questions like these!  https://snorkel.readthedocs.io/en/v0.9.3/packages/_autosummary/labeling/snorkel.labeling.LabelModel.html#snorkel.labeling.LabelModel
