### ISSUE TITLE
can't install snorkel

### ISSUE THREAD

**Issue by dslim23** [snorkel-team/snorkel#1514]
## Issue description

Tried to install snorkel, couldn't get it work 
```
pip install snorkel
```
```
ERROR: Could not find a version that satisfies the requirement snorkel (from versions: none)
ERROR: No matching distribution found for snorkel
```

## Expected behavior
snorkel installs 
## System info

* How you installed Snorkel (conda, pip, source):
* Build command you used (if compiling from source):
* OS:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
* Python version: 3.5
* Snorkel version:
* Versions of any other relevant libraries: pip 19.3.1

**Comment by vincentschen** [comment]
[Snorkel](https://pypi.org/project/snorkel/) requires Python >= 3.6. Can you try upgrading your Python version?

**Comment by dslim23** [comment]
thanks! works like a charm now. i'd suggest putting that requirement on the main README.md more prominently!

**Comment by govardhan100** [comment]
snorkel required python >=3.6 and it is better to install with conda https://www.snorkel.org/use-cases/
