### ISSUE TITLE
Pass arguments to labelling functions via LFApplier.apply()

### ISSUE THREAD

**Issue by chaturv3di** [snorkel-team/snorkel#1515]
I'm writing labelling functions that read pandas DataFrames and process the text column. I want my modelling pipeline to be generic and consume DataFrames created by different sources, which means that different DataFrames have different columns and the relevant text columns can have different names.

I could of course do this via slicing the input DataFrame and renaming the columns at the time of calling the `apply()` method. But it should be possible to pass the column names (and possibly more parameters) to labelling functions via additional keyword arguments in `LFApplier.apply()` method. This should require no more than a minor change in method signatures. 

Is it okay for me to create a PR for this?

**Comment by henryre** [comment]
Hi @chaturv3di, thanks for posting! Can you post a code example with the desired functionality?

**Comment by chaturv3di** [comment]
Suppose my use case is identifying phishing or some other scam. I'm writing regex based labeling functions that look like the following:

```python
@labeling_function()
def scam_buy_fast(doc):
    patterns = ['pric', 'buy', 'instant', 'quick', 'limited',
                'at\s*home', 'hurry', 'now', 'today',
                'apply|act|email|call|contact|write']
    threshold = 2
    if occurrences_of(patterns, doc) >= threshold:
        return SCAM
    return ABSTAIN
```

Here the method `occurrences_of()` returns the number of times one of the `patterns` appears in `doc`. The labeling function returns a vote based on the `threshold`. A simple case is when I'd want to assign `threshold` through an argument.

It would be great if I could create my weakly labelled data set as `wl_dataset = applier.apply(unlabelled_dataset, **kwargs)` where `apply()` simply passes the keyword arguments to all the labeling functions. So, my labeling function would become the following.

```python
@labeling_function()
def scam_buy_fast(doc, **kwargs):
    patterns = ['pric', 'buy', 'instant', 'quick', 'limited',
                'at\s*home', 'hurry', 'now', 'today',
                'apply|act|email|call|contact|write']

    # Check if threshold can be set from arguments
    threshold = None
    try:
        threshold = int(kwargs['scam_pattern_threshold'])
    except (KeyError, ValueError):
        threshold = 2

    if occurrences_of(patterns, doc) >= threshold:
        return SCAM
    return ABSTAIN
```

This is especially useful when LFs use third-party APIs. Furthermore, I can treat some of these keyword arguments as hyper-parameters in the overall modelling pipeline.

Does this make sense?

**Comment by henryre** [comment]
Hi @chaturv3di, got it, thanks for the detail. The `resources` parameter for labeling functions is typically how we programmatically pass arguments besides the data points themselves. For example:

```python
def scam_buy_fast(doc, threshold=None):
     ...

def another_threshold_lf(doc, threshold=None):
    ...

threshold = 2
fs_threshold = [scam_buy_fast, another_threshold_lf]
lfs_threshold = [LabelingFunction(f.__name__, f, resources=dict(threshold=threshold)) for f in fs]
applier = LFApplier(lfs_threshold)
dataset = applier.apply(X)
```

One of our design choices was to keep as much logic encapsulated in the LF/TF/SF/Policy objects as possible, rather than in applier construction or calls. Will the setup above work for your use case?

**Comment by ajratner** [comment]
Closing for now, feel free to re-open!
