### ISSUE TITLE
Implementation of label model from "Training Complex Models with Multi-Task Weak Supervision" 

### ISSUE THREAD

**Issue by abenton** [snorkel-team/snorkel#1517]
Thank you for all of the hard work put in designing snorkel and accompanying examples.

Issue
----

I have been digging into the code, trying to understand how the label model is fit.  I do not see how the loss function that is minimized in your code: https://github.com/snorkel-team/snorkel/blob/64c8741ef876285ed3ae0544b35fc1fe99191f2d/snorkel/labeling/model/label_model.py#L541-L557

would result in the same \hat{\mu} as the objective described in Algorithm 1 of your 2019 AAAI paper:

![image](https://user-images.githubusercontent.com/806288/69178496-b4747980-0ad7-11ea-8ab2-ded061374aae.png)

This question was previously brought up in https://github.com/snorkel-team/snorkel/issues/1462#issuecomment-533937045, but was not answered as far as I can tell.  For example, it looks like Algorithm 1 depends on the generalized inverse of a covariance matrix, but I cannot find any place snorkel codebase where a matrix inverse is taken.

Is the loss function being minimized in label_model.py a special case of Algorithm 1 when all labeling functions are independent given the label and we only have one task?  Is there a simple linear algebra derivation to show these are equivalent problems?  If so, what is this derivation?

Any help you can give me is much appreciated!  Thanks!

**Comment by ajratner** [comment]
Hi @abenton thanks for the question!  As noted in my response to #1462, the current master branch implementation handles the conditionally independent sub-case.  Regarding showing equivalence, you can start with the fact that in this simpler model the covariance will be diagonal.  There are some additional notes that might be helpful in my phd thesis intro (posted at my website).  Hope this helps!
