### ISSUE TITLE
ModuleNotFoundError: No module named Dask when I want to use PandasParallelLFApplier

### ISSUE THREAD

**Issue by hcvazquez** [snorkel-team/snorkel#1521]
## Is your feature request related to a problem? Please describe.
When I want to use PandasParallelLFApplier I get a ModuleNotFoundError

## Describe the solution you'd like
Since you need Dask to execute some parallel code in snorkel, why not add Dask as an essential requirement. 

## Describe alternatives you've considered
The alternative is install Dask each time that you work with large amounts of data. However, if the developer has the responsibility we can have version errors.

**Comment by bhancock8** [comment]
Thanks for posting! 

Dask appears to be a requirement already: https://github.com/snorkel-team/snorkel/blob/056bf91c62f8c28a47e90d6f90d8ac579e2bbd32/requirements.txt#L37

Can you post more details about how you installed `snorkel` and what your environment is?

**Comment by hcvazquez** [comment]
Yes, you're right. Thanks for answering.

I just run "pip install snorkel". I only see a torchvision Error.

This is the full output:
`$ pip install snorkel
Collecting snorkel
  Downloading https://files.pythonhosted.org/packages/ff/f4/a0e419793075b737f1e86a1642d676dfdb17859887542afa06915136c231/snorkel-0.9.3-py3-none-any.whl (139kB)
     |████████████████████████████████| 143kB 22.5MB/s
Requirement already satisfied: scipy<2.0.0,>=1.2.0 in /usr/local/lib/python3.7/site-packages (from snorkel) (1.3.1)
Collecting pandas<0.26.0,>=0.25.0 (from snorkel)
  Downloading https://files.pythonhosted.org/packages/63/e0/a1b39cdcb2c391f087a1538bc8a6d62a82d0439693192aef541d7b123769/pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl (10.4MB)
     |████████████████████████████████| 10.4MB 52.4MB/s
Requirement already satisfied: numpy<2.0.0,>=1.16.0 in /usr/local/lib/python3.7/site-packages (from snorkel) (1.17.2)
Collecting networkx<2.4,>=2.2 (from snorkel)
  Downloading https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip (1.7MB)
     |████████████████████████████████| 1.8MB 58.8MB/s
Collecting tensorboardX<2.0,>=1.6 (from snorkel)
  Downloading https://files.pythonhosted.org/packages/a6/5c/e918d9f190baab8d55bad52840d8091dd5114cc99f03eaa6d72d404503cc/tensorboardX-1.9-py2.py3-none-any.whl (190kB)
     |████████████████████████████████| 194kB 31.7MB/s
Collecting torch<1.2.0,>=1.1.0 (from snorkel)
  Downloading https://files.pythonhosted.org/packages/ac/23/a4b5c189dd624411ec84613b717594a00480282b949e3448d189c4aa4e47/torch-1.1.0-cp37-cp37m-manylinux1_x86_64.whl (676.9MB)
     |████████████████████████████████| 676.9MB 111kB/s
Requirement already satisfied: tqdm<5.0.0,>=4.33.0 in /usr/local/lib/python3.7/site-packages (from snorkel) (4.38.0)
Collecting munkres==1.1.2 (from snorkel)
  Downloading https://files.pythonhosted.org/packages/64/97/61ddc63578870e04db6eb1d3bee58ad4e727f682068a7c7405edb8b2cdeb/munkres-1.1.2-py2.py3-none-any.whl
Requirement already satisfied: scikit-learn<0.22.0,>=0.20.2 in /usr/local/lib/python3.7/site-packages (from snorkel) (0.21.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/site-packages (from pandas<0.26.0,>=0.25.0->snorkel) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/site-packages (from pandas<0.26.0,>=0.25.0->snorkel) (2019.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.7/site-packages (from networkx<2.4,>=2.2->snorkel) (4.4.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from tensorboardX<2.0,>=1.6->snorkel) (1.12.0)
Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.7/site-packages (from tensorboardX<2.0,>=1.6->snorkel) (3.9.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/site-packages (from scikit-learn<0.22.0,>=0.20.2->snorkel) (0.13.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from protobuf>=3.8.0->tensorboardX<2.0,>=1.6->snorkel) (41.0.1)
Building wheels for collected packages: networkx
  Building wheel for networkx (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/de/63/64/3699be2a9d0ccdb37c7f16329acf3863fd76eda58c39c737af
Successfully built networkx
ERROR: torchvision 0.4.2 has requirement torch==1.3.1, but you'll have torch 1.1.0 which is incompatible.
Installing collected packages: pandas, networkx, tensorboardX, torch, munkres, snorkel
  Found existing installation: pandas 0.24.2
    Uninstalling pandas-0.24.2:
      Successfully uninstalled pandas-0.24.2
  Found existing installation: torch 1.3.1
    Uninstalling torch-1.3.1:
      Successfully uninstalled torch-1.3.1
Successfully installed munkres-1.1.2 networkx-2.3 pandas-0.25.3 snorkel-0.9.3 tensorboardX-1.9 torch-1.1.0
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

And this is the full "pip freeze" after the installation:

` pip freeze
absl-py==0.8.0
asn1crypto==0.24.0
astor==0.8.0
attrs==19.1.0
autovizwidget==0.13.1
backcall==0.1.0
beautifulsoup4==4.8.1
bitarray==1.1.0
bleach==3.1.0
blis==0.4.1
boto3==1.10.24
botocore==1.13.24
Bottleneck==1.3.1
catalogue==0.0.8
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
colorama==0.3.9
cryptography==2.7
cycler==0.10.0
cymem==2.0.3
Cython==0.29.14
decorator==4.4.0
defusedxml==0.6.0
docutils==0.15.2
entrypoints==0.3
fastai==1.0.42
fastprogress==0.1.22
fsspec==0.6.0
future==0.18.2
gast==0.3.2
google-pasta==0.1.7
grpcio==1.24.0
h5py==2.10.0
hdijupyterutils==0.13.1
idna==2.8
importlib-metadata==0.23
impyla==0.15a1
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
JayDeBeApi==1.1.1
jedi==0.15.1
Jinja2==2.10.1
jmespath==0.9.4
joblib==0.13.2
JPype1==0.6.3
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.3
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterlab==0.35.6
jupyterlab-git==0.6.0
jupyterlab-server==0.2.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
melitk.analytics==1.3.5
melitk.fda==1.0.0
mistune==0.8.4
mock==3.0.5
more-itertools==7.2.0
munkres==1.1.2
murmurhash==1.0.2
nbconvert==5.6.0
nbformat==4.4.0
networkx==2.3
nmslib==2.0.5
nose==1.3.7
notebook==5.7.5
ntlm-auth==1.4.0
numexpr==2.7.0
numpy==1.17.2
nvidia-ml-py3==7.352.0
packaging==19.2
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.1
plac==1.1.3
plotly==4.1.1
ply==3.11
preshed==3.0.2
presto-python-client==0.7.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.9.2
psutil==5.6.3
psycopg2-binary==2.8.4
ptyprocess==0.6.0
pyarrow==0.15.1
pyasn1==0.4.7
pybind11==2.4.3
pycparser==2.19
Pygments==2.4.2
PyHive==0.6.1
pykerberos==1.2.1
pyparsing==2.4.5
pyrsistent==0.15.4
python-dateutil==2.8.0
python-dotenv==0.10.3
pytz==2019.2
pywinrm==0.3.0
PyYAML==5.1.2
pyzmq==18.1.0
qadb-transactional-questions-classifier==0.0.1.dev0
qtconsole==4.5.5
requests==2.22.0
requests-kerberos==0.12.0
requests-ntlm==1.1.0
retrying==1.3.3
rsa==3.4.2
s3fs==0.4.0
s3transfer==0.2.1
sasl==0.2.1
scikit-learn==0.21.1
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
snorkel==0.9.3
soupsieve==1.9.5
spacy==2.2.3
sparkmagic==0.13.1
srsly==0.2.0
tensorboard==1.14.0
tensorboardX==1.9
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
thinc==7.3.1
thrift==0.9.3
thrift-sasl==0.2.1
thriftpy==0.3.9
thriftpy2==0.4.0
torch==1.1.0
torchvision==0.4.2
tornado==6.0.3
tqdm==4.38.0
traitlets==4.3.2
typing==3.7.4.1
urllib3==1.25.6
wasabi==0.4.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
xmltodict==0.12.0
zipp==0.6.0`

I am going to close the issue since it seems an error on my part.

**Comment by bhancock8** [comment]
You're not wrong, @hcvazquez. It's included in `requirements.py`, but not `setup.py` so that it won't be a hard requirement for the pip package. We do that because it's not a core requirement (i.e. parallel processing is fully optional), and we want to keep the required dependencies as light as possible.
