### ISSUE TITLE
It seems the jupyter viewer is not exist in current version?

### ISSUE THREAD

**Issue by mrbeann** [snorkel-team/snorkel#1522]
It will be great if some widgets can be added for viewer.

**Comment by ajratner** [comment]
Hi @mrbeann for now we have moved all data modality / problem type-specific features (e.g. the viewer for relation extraction) out of this repo, and in this case into the [snorkel-extraction](https://github.com/snorkel-team/snorkel-extraction) repo.  Our goal is to maintain this library as a minimal, modular package that is data type / domain agnostic!  For more thoughts here see our release notes on v0.9: https://www.snorkel.org/blog/hello-world-v-0-9
