### ISSUE TITLE
update torch version from 1.1.0 to 1.3.1

### ISSUE THREAD

**Issue by antw-cg** [snorkel-team/snorkel#1526]
## Is your feature request related to a problem? Please describe.
Other dependencies for my project like torchvision==0.4.2, fast-bert==1.5.0, allennlp==0.9.0 all require that at least torch>=1.2.0, some require torch>=1.3.1, while snorkel uses 1.1.0

## Describe the solution you'd like
Update torch dependency to 1.3.1

## Describe alternatives you've considered
I can have separate environments for running snorkel and running actual NLP, but that's a messy solution and dependencies should be up to date anyways

**Comment by henryre** [comment]
Hi @antw-cg, thanks for posting! This has been on our radar, and I drafted an (incomplete) upgrade PR a little while ago in #1395. Tagging as help-wanted in case anyone wants to push it over the goal line.
