### ISSUE TITLE
Extract candidates in 0.9.3 version

### ISSUE THREAD

**Issue by maciejbiesek** [snorkel-team/snorkel#1527]
## Issue description

I am wondering how can I extract candidates that are not full sentences. In the previous version there was an ability to create the session to database and use predefined extractors (n-grams, nlp, regex based). Is there any option to do it now?

**Comment by ajratner** [comment]
Hi @maciejbiesek we moved the relation extraction-specific functionality to [snorkel-extraction](https://github.com/snorkel-team/snorkel-extraction).  It's not up to date or being actively maintained, but it is available there.  Also see our notes on v0.9 [here](https://www.snorkel.org/blog/hello-world-v-0-9).
