### ISSUE TITLE
UnsatisfiableError when installing snorkel==0.9.0 through conda

### ISSUE THREAD

**Issue by qysnn** [snorkel-team/snorkel#1531]
I first used `conda install snorkel -c conda-forge` to install snorkel on Windows 10, Anaconda 2019.10. It went successfully. Unfortunately, I got `ModuleNotFoundError: No module named 'snorkel.labeling'` error when I try to use it. Following other issues who have the same problem, I tried to use `conda install snorkel==0.9.0 -c conda-forge` to install the 0.9.0 as indicated in the readme. But I got the UnsatisfiableError:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package tqdm conflicts for:
snorkel==0.9.0 -> tqdm[version='>=4.29.0,<5.0.0']
Package sqlite conflicts for:
python=3.6 -> sqlite[version='>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0']
Package numpy conflicts for:
snorkel==0.9.0 -> numpy[version='>=1.16.0,<2.0.0']
Package vc conflicts for:
python=3.6 -> vc[version='14.*|>=14,<15.0a0|>=14.1,<15.0a0']
Package pandas conflicts for:
snorkel==0.9.0 -> pandas[version='>=0.24.0,<0.25.0']
Package pip conflicts for:
python=3.6 -> pip
Package scikit-learn conflicts for:
snorkel==0.9.0 -> scikit-learn[version='>=0.20.2,<0.22.0']
Package scipy conflicts for:
snorkel==0.9.0 -> scipy[version='>=1.2.0,<2.0.0']
Package vs2015_runtime conflicts for:
python=3.6 -> vs2015_runtime[version='>=14.16.27012,<15.0a0']
Package pytorch conflicts for:
snorkel==0.9.0 -> pytorch[version='>=1.1.0,<1.2.0']
Package networkx conflicts for:
snorkel==0.9.0 -> networkx[version='>=2.2,<3.0']
Package tensorboardx conflicts for:
snorkel==0.9.0 -> tensorboardx[version='>=1.6,<2.0']
```

**Comment by brahmaneya** [comment]
Can you try installing the latest version (0.9.3)? We have pushed a number of fixes between the two versions.

**Comment by regstrtn** [comment]
I was facing the same issue. If you are on Windows 10, use the Windows Linux subsystem to run ubuntu inside windows and install python + snorkel on linux. Steps: 
1. Control Panel > Programs & Features > Turn Windows features on or off
2. Tick mark the "Windows subsystem for Linux" feature there. (May need to restart).
3. Go to Windows app store and install ubuntu from there (it will install like a normal software). 
4. Launch ubuntu from Start Menu, it will open up like a bash shell running on Windows. You can then use it as bash shell. You windows drives (C: and D: etc) will be accessible from `cd /mnt/` folder.
