### ISSUE TITLE
Using Labeling Functions for multi-class classification problems

### ISSUE THREAD

**Issue by stenpiren** [snorkel-team/snorkel#1532]
I have seen the tutorial on the spam classification where among other things, it is taught how to use labeling and transformation functions. But I see a limitation of the features snorkel provides when it comes to multi-class classification, as this example is strictly meant for a binary classification problem.

Isn't it better to include more features or perharps add an example where we can see the use of snorkel in order to label more than 3 classes.  

For instance I have a problem involving 20 classes. For what I see as work around is to use labeling functions per each class, for instance treating each class one at a time as if it is a binary case.

The best would be to tackle all in one go, any suggestion besides the one I am thinking about?

**Comment by brahmaneya** [comment]
Hi @stenpiren, you can check out the `visual_relation` tutorial, which deals with a non-binary problem.

**Comment by stenpiren** [comment]
It would have been interesting to see one similar to spam/ham problem but with multiclass. The ```visual_relation``` want is a bit complicated as it involves text and image.
