### ISSUE TITLE
Torch install failure when using requirements.txt

### ISSUE THREAD

**Issue by drewbyh** [snorkel-team/snorkel#1542]
## Issue description

When running 'pip install -r requirements.txt' I get the following error on the Torch install:

ERROR: Could not find a version that satisfies the requirement torch<1.2.0,>=1.1.0 (from -r requirements.txt (line 21)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch<1.2.0,>=1.1.0 (from -r requirements.txt (line 21))

All installs before Torch are successful.

## Code example/repro steps

ERROR: Could not find a version that satisfies the requirement torch<1.2.0,>=1.1.0 (from -r requirements.txt (line 21)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch<1.2.0,>=1.1.0 (from -r requirements.txt (line 21))

## Expected behavior
Required Torch version should install correctly.

## Screenshots
No screenshots of code!

## System info

* How you installed Snorkel (conda, pip, source):
* Build command you used (if compiling from source): pip install -r requirements.txt
* OS:  Windows 10 Build 1809
* Python version: 3.8
* Snorkel version:
* Versions of any other relevant libraries:

**Comment by stenpiren** [comment]
I have exactly the same problem. Not just when installing from requirements.txt but a simply pip install snorkel falls with the same error code: 

```Could not find a version that satisfies the requirement torch<1.2.0,>=1.1.0 (from snorkel) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch<1.2.0,>=1.1.0 (from snorkel)```

Also, the requirements.txt fail in most of the tutorials. Same error code.

**Comment by MortenKP** [comment]
I have the same problem as well.

**Comment by MortenKP** [comment]
Installing one of these before "pip install snorkel" solved it for me:
# CUDA 9.0
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch

# CUDA 10.0
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch

# CPU Only
conda install pytorch-cpu==1.1.0 torchvision-cpu==0.3.0 cpuonly -c pytorch

Source: https://pytorch.org/get-started/previous-versions/

**Comment by henryre** [comment]
Thanks for posting your solution @MortenKP ! We have a [note on using `conda` with PyTorch in the README](https://github.com/snorkel-team/snorkel#installation) but feel free to propose a clearer description! Going to close this out, but feel free to re-open if needed!
