### ISSUE TITLE
tqdm warning during LF call

### ISSUE THREAD

**Issue by maximrus23** [snorkel-team/snorkel#1556]
## Issue description

tqdm warning use of panel while applying Labeling function

## Code example/repro steps
```python 
from snorkel.labeling import PandasLFApplier

lfs = [check_out, check]

applier = PandasLFApplier(lfs=lfs)
L_train = applier.apply(df=df_train)
```

## Warning 
/opt/anaconda3/lib/python3.7/site-packages/tqdm/std.py:658: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
from pandas import Panel

## System info

* How you installed Snorkel  pip
* Build command you used (if compiling from source):
* OS: MAC AS
* Python version: 3 
* Snorkel version: latest 
* Versions of any other relevant libraries:

## Additional context
Just raising this because Pandas was updated to 1.0.1. I still use other version but on a new version this warning may become an issue.

**Comment by ajratner** [comment]
Hi @maximrus23 thanks for the heads up here, we'll track this for when we upgrade pandas support
