### ISSUE TITLE
Support Pytorch > 1.1.0

### ISSUE THREAD

**Issue by blackr2d** [snorkel-team/snorkel#1558]
## Issue description

Installation with pip fails with

`ERROR: Could not find a version that satisfies the requirement torch<1.2.0,>=1.1.0 (from snorkel) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch<1.2.0,>=1.1.0 (from snorkel)`

## Code example/repro steps

`pip install snorkel`

Results in error as above. torch versions listed are not available.
Any reason torch 1.4 cannot be used?

## Expected behavior

Successful install

## System info

* How you installed Snorkel (conda, pip, source):
pip
* Build command you used (if compiling from source):
* OS:
Windows 7 x64, Windows 10 x64, RHEL 7.5
* Python version:
3.7.4
* Snorkel version:
Current (0.9.3)
* Versions of any other relevant libraries:
None, clean environment

## Additional context

There seems to be little development and no releases for months now, that's why the requirements are impossible to meet anymore, is the project dead?

**Comment by vincentschen** [comment]
At the moment, `snorkel` requires [`torch>=1.1.0,<1.2.0`](https://github.com/snorkel-team/snorkel/blob/master/requirements.txt#L21).

We have an upgrade planned but also welcome community support here!

**Comment by maxmcl** [comment]
@blackr2d try installing with `python=3.6`, this should fix it. Also on their readme, they mention enabling the Linux kernel on Windows

**Comment by lukehsiao** [comment]
[Fonduer](https://github.com/hazyresearch/fonduer) would also benefit with an upgrate on snorkel's torch dependency to be something like "torch>=1.3.1,<2.0.0".

**Comment by vincentschen** [comment]
Hi all — `torch>=1.2` is now supported in the latest release, `snorkel==0.9.5`.

**Comment by blackr2d** [comment]
Thank you! Confirmed working.
