### ISSUE TITLE
Documentation link to 'latest' is broken and shows old docs

### ISSUE THREAD

**Issue by rjurney** [snorkel-team/snorkel#1575]
## Issue description

The latest docs, v0.9.5, are here: https://snorkel.readthedocs.io/en/v0.9.5/

The 'latest' tag for docs are here: https://snorkel.readthedocs.io/en/latest/

This looks like an old API and is not I think the latest (v0.9.5). This should be fixed :)

**Comment by vincentschen** [comment]
You're right, should be fixed :).

Should be updated now!
