### ISSUE TITLE
Inconsistency between documentation and module

### ISSUE THREAD

**Issue by TrigonaMinima** [snorkel-team/snorkel#1577]
## Issue description

Following through the [getting started page](https://www.snorkel.org/get-started/), the following import statements are giving me import errors

```python
from snorkel.labeling import LabelModel, PandasLFApplier

# produces
# ImportError: cannot import name 'LabelModel' from 'snorkel.labeling'
```

What worked for me instead was:

```python
from snorkel.labeling import model
from snorkel.labeling.apply import pandas as apply
...
model.LabelModel()
apply.PandasLFApplier()
```

## System info

* installed through pip
* OS: `5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Python version: `3.7.7`
* Snorkel version: `0.9.5`

**Comment by johncalab** [comment]
Yeah, I had the same issue. I pip installed 0.9.3, which is the version used in the tutorials and it worked.

**Comment by vincentschen** [comment]
You're right — the tutorials (and website link) are not up to date with the latest version of Snorkel Flow.. we'll get this resolved shortly!

**Comment by vincentschen** [comment]
thanks for raising — this should now be resolved with https://github.com/snorkel-team/snorkel-tutorials/pull/216!

**Comment by EasonC13** [comment]
You can try this instead. 
It works for me.

```
from snorkel.labeling.model.label_model import LabelModel
```

You can check the latest document for how to import the module you want.

https://snorkel.readthedocs.io/en/v0.9.7/packages/_autosummary/labeling/snorkel.labeling.model.label_model.LabelModel.html
