### ISSUE TITLE
Add support of pandas >=1.0

### ISSUE THREAD

**Issue by dchichkov** [snorkel-team/snorkel#1582]
Description of the problem:
```
ERROR: snorkel 0.9.5 has requirement pandas**<0.26.0**,>=0.25.0, but you'll have pandas 1.0.3 which is incompatible.
ERROR: snorkel 0.9.5 has requirement scikit-learn**<0.22.0**,>=0.20.2, but you'll have scikit-learn 0.22.2.post1 which is incompatible.
```
It'd be good to remove or relax upper constraints on the module versions.  Is there a good reason why these are included, or is it just out of precaution?

**Comment by ajratner** [comment]
@dchichkov we'll look into shortly, as well as the related PR- thanks for contributing!

**Comment by rchliu** [comment]
has there been any update on this?

**Comment by vincentschen** [comment]
@rchliu Resolved the tests in https://github.com/snorkel-team/snorkel/pull/1584 and merged— thanks for your patience!
