### ISSUE TITLE
Upgrade Torch to >= 1.2.0

### ISSUE THREAD

**Issue by rjurney** [snorkel-team/snorkel#1583]
## Is your feature request related to a problem? Please describe.

I thought torch was going to get upgraded soon but I don't see it in v0.9.3 and I don't see a ticket on it.

## Describe the solution you'd like

Update Torch to the highest version you can.

**Comment by bhancock8** [comment]
This update was made in #1565 and is a part of v0.9.5. We now support 1.2.0 to 2.0.

**Comment by rjurney** [comment]
I think I was having v0.9.3 flashbacks
