### ISSUE TITLE
List of inbuilt metrics in score page of label model

### ISSUE THREAD

**Issue by TrigonaMinima** [snorkel-team/snorkel#1585]
## Is your feature request related to a problem? Please describe.
In the documentation page of label model score ([here](https://snorkel.readthedocs.io/en/master/packages/_autosummary/labeling/snorkel.labeling.model.label_model.LabelModel.html?highlight=score#snorkel.labeling.model.label_model.LabelModel.score)), the list of possible metrics are not listed. I had to go through the source to find the inbuilt methods. This the page where I found them :https://github.com/snorkel-team/snorkel/blob/c4e24fbd4b5ff4b9c64298ead2ca0f66d04819d5/snorkel/analysis/metrics.py#L110-L121

It'll also help if examples are present for the user-defined metrics to know how to build one.

## Describe the solution you'd like
The list can be updated in the function doc to show the inbuilt ones present.

**Comment by vincentschen** [comment]
@TrigonaMinima thanks for pointing this out! You're right— our docs can be better here. Feel free to open a PR. Otherwise, this is on our queue!
