### ISSUE TITLE
Spam tutorial error: The system cannot find the file specified

### ISSUE THREAD

**Issue by melboswell** [snorkel-team/snorkel#1588]
Hello,

I am new to using snorkel, but have followed the instructions to install it on Windows using conda and create and activate a virtual environment. I am trying to go through the spam tutorial, but am running into the following error:

![image](https://user-images.githubusercontent.com/43861597/81758333-5321d780-9476-11ea-9c1e-f2e53b977b37.png)

**Comment by bhancock8** [comment]
Bummer! Windows is always trickier. I'm glad to see you were able to set up the virtual environment. Did you also follow the suggestion in the "A quick note for Windows users" section about running in Docker or the Linux subsystem? That will give you the best chance of success.

**Comment by melboswell** [comment]
Thanks for the response.  I actually found that if I remove ".models" from import snorkel.labeling.modes (so it is just snorkel, labeling), in the utils script then the problem resolves. I also had to change the function node to nodes in graph_utils.py

**Comment by bhancock8** [comment]
The node -> nodes change sounds like a requirements issue (the wrong version of networkx being used). See #1491 for more detail there. You may want to check how your virtual environment is being created and used. Regardless, I'm glad you got it working!
