### ISSUE TITLE
Understanding LabelModel and cardinality

### ISSUE THREAD

**Issue by paulachocron** [snorkel-team/snorkel#1591]
I'm seeing some strange predictions on my data. I have labels 0 and 1. I defined 5 labeling functions which sometimes abstain. 

When I train a LabelModel with cardinality=2 (the real value), it predicts always 0. I see points where 4 lfs return 1, one abstains, and the predictions is 0. Even points where all lfs return 1, yet the model predicts 0. When I set cardinality=3 results seem much more reasonable. But it's not the real value!

Any thoughts on what could be happening?

This is my `LFAnalysis(L_train).lf_summary()`

 | Polarity | Coverage | Overlaps | Conflicts
 -- | -- | -- | -- | --
0 | [0, 1] | 0.708946 | 0.708902 | 0.501723
1 | [0, 1] | 0.884765 | 0.884285 | 0.615824
2 | [0, 1] | 0.872596 | 0.871811 | 0.601038
3 | [0, 1] | 0.830985 | 0.830811 | 0.602303
4 | [0, 1] | 0.450735 | 0.450735 | 0.355084

**Comment by paroma** [comment]
You can try changing parameters like class_balance and regularization to see whether that gives better results (see [this tutorial](https://github.com/snorkel-team/snorkel-tutorials/blob/b4926576f5042c24de90a9da2286e4c639dd480f/crowdsourcing/crowdsourcing_tutorial.ipynb) and [documentation](https://snorkel.readthedocs.io/en/v0.9.6/packages/_autosummary/labeling/snorkel.labeling.model.label_model.LabelModel.html?highlight=label_model#snorkel.labeling.model.label_model.LabelModel.fit) for examples).

We can also help debug further here if we have access to the `L` matrix for this data.
