### ISSUE TITLE
Compatibility with latest pandas dependency.

### ISSUE THREAD

**Issue by donpellegrino** [snorkel-team/snorkel#1599]
It would be easier to work with snorkel if it was compatible with the latest release of pandas. Installing snorkel with pip triggers a downgrade of pandas. Pandas is 1.0.5 at the time of this issue submission.

**Comment by michael-erasmus** [comment]
👍 to this. I'm getting lot's of issues with Colab not being compatible with the version of Pandas that Snorkel needs. Curious if there are any plans to be compatible with a newer version of Pandas soon?

**Comment by michael-erasmus** [comment]
@donpellegrino just saw this related issue and PR:

https://github.com/snorkel-team/snorkel/issues/1582
https://github.com/snorkel-team/snorkel/pull/1584

**Comment by bhancock8** [comment]
Resolved in #1584. Feel free to reopen if you're still having issues!

**Comment by michael-erasmus** [comment]
Thanks so much @bhancock8!
