### ISSUE TITLE
How do I use a continuous feature/variable/column of a dataset as a Labeling function in snorkel?

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [snorkel-team/snorkel#1600]
Hi Team,

I want to use a continuous normalized column of my dataset as one of the signals for training my snorkel model. How do I accomplish this? I can only see examples with categorical columns/variables being used as labeling functions. Does it mean I need t set some form of a threshold for the continuous variable? 

Thanks in advance!

**Comment by bhancock8** [comment]
Yep, that's right! Labeling functions output a discrete label (or abstain), so if they're based on one or more continuous output, you'll need to map those into discrete labels somehow (such as with a threshold, bounding box, or other numeric comparison).

**Comment by soumya-ranjan-sahoo** [comment]
Alright. Thanks for your feedback.  Well, how should I go about a column with already having binary labels (0,1) to be used as a labeling function? An example should help :)

**Comment by bhancock8** [comment]
I may be misunderstanding here, but if you have a column that already has binary labels, then you can basically just map those to labels in the labeling function. So for a problem with classes [A, B, C] and a column called "my_column" with binary values, then you could write (in pseudocode)"lf(x): if x['my_column'] == 1, then label A else abstain."

**Comment by soumya-ranjan-sahoo** [comment]
Okay! So in the above example, the data point with abstain doesn't get a label, right? 
Basically for a binary classifier with labels (1,0) with positive = 1, abstain = 0, and if I define a labeling function as -  def LF1(x):
    return POSITIVE if  x.TextLength > 10 else ABSTAIN, I will get a 100% coverage with this labeling function? 
Am I right with this as abstain in my case would be 0 but in your example it won't.

**Comment by bhancock8** [comment]
Ah, that's the difference. For a binary classification problem, your LFs will output one of {positive = 1, negative = 0, abstain = -1}, where abstaining meanings no label is added to the data point from that LF. And then your classifier will output one of {positive = 1, negative = 0}. Voting negative is different than abstaining from voting.
