### ISSUE TITLE
ModuleNotFoundError: No module named 'snorkel.labeling'

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [snorkel-team/snorkel#1601]
I installed snorkel using conda and when I try to run - from snorkel.labeling import labeling_function it throws the following error - ModuleNotFoundError: No module named 'snorkel.labeling'.

I tried looking up for a solution on Github, but unfortunately, I couldn't follow through. I have also tried installing nb_conda_kernels, to make all your conda environments available in jupyter but it didn't help. Also tried creating a separate env, installing snorkel and launching jupyter notebook from the snorkel's environment, and it didn't work either. Any form of help is much appreciated!

**Comment by bhancock8** [comment]
Hmm, let's collect a few more details.
- What operating system are you running on? 
- When you run `pip freeze | grep snorkel`, what version does it report you have installed?
- Are you able to import other modules from snorkel besides `snorkel.labeling`? e.g., does `import snorkel` work?

**Comment by soumya-ranjan-sahoo** [comment]
I was able to troubleshoot the issue. Thanks for your support :)

**Comment by soumya-ranjan-sahoo** [comment]
I was able to troubleshoot the issue. Thanks for your support :)
