### ISSUE TITLE
SliceAwareClassifier with TensorFlow model

### ISSUE THREAD

**Issue by OlegDurandin** [snorkel-team/snorkel#1607]
Hi all,

I've just started using Snorkel, but unfortunatelly faced with one issue.
I'd like to use slice-based approach to my TensorFlow model.

But in according to documentation `SliceAwareClassifier` (https://snorkel.readthedocs.io/en/v0.9.6/packages/_autosummary/slicing/snorkel.slicing.SliceAwareClassifier.html#snorkel.slicing.SliceAwareClassifier) require Torch neural network module.

Can I use SliceAwareClassifier with TensorFlow model? Or may be there is exists some approaches to using slice-based with TensorFlow models?

Thank you in advice, 
Oleg

**Comment by vincentschen** [comment]
Hi @OlegDurandin — our implementation is in PyTorch, but there should be no fundamental blockers to use slice-based learning in Tensorflow. We're open to PRs support here as well!
