### ISSUE TITLE
 multiclass label scorer

### ISSUE THREAD

**Issue by Evelyn-Xin** [snorkel-team/snorkel#1609]
Hello, I am currently do an experiment use multicalss labels. But the error shows "ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted']." 
Since the scorer could defined by users, how can I change the scorer, may be use golds and preds?

**Comment by vincentschen** [comment]
Hi @Evelyn-Xin — do you mind sharing the parameters that you're passing into the `Scorer` as well, include samples of the golds/preds?
