### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by HCelion** [snorkel-team/snorkel#1611]
## Issue description

I try to install `snorkel` via `pip` and get an error

`ERROR: Could not find a version that satisfies the requirement torch<2.0.0,>=1.2.0 (from snorkel) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch<2.0.0,>=1.2.0 (from snorkel)`

## Code example/repro steps

`pip install snorkel`

## System info

* How you installed Snorkel (conda, pip, source):
* Build command you used (if compiling from source):
* OS: Windows
* Python version: 3.8.3
* Snorkel version:
* Versions of any other relevant libraries: -

**Comment by henryre** [comment]
Hi @HCelion , it looks like the set of available PyTorch versions in the package repo you're using is limited compared to the ones available on PyPI (https://pypi.org/project/torch/#history). Are you using an internal mirror of PyPI, Conda, or something similar?

**Comment by HCelion** [comment]
Hi @henryre, that might be it, as I did it from the company computer. I guess I can close the issue and reopen it if I can't find a way around. Thanks for the quick reply!
