### ISSUE TITLE
SwellShark implementation

### ISSUE THREAD

**Issue by YiranChe** [snorkel-team/snorkel#1612]
Dear Snorkel Team, I saw on your issues that you implemented the SwellShark algorithm. I didn't find it in the documentation. I'm wondering whether you could tell me which function is SwellShark. Thank you so much!

**Comment by jason-fries** [comment]
Hi @YiranChe,
We never released the original SwellShark code, but there is a [newer paper](https://arxiv.org/abs/2008.01972) that implements NER tagging using Snorkel. This paper removes the need to identify candidate entities _a priori_ before training your labeling model and provides library code for autogenerating dictionary labeling functions from knowledge bases like the Unified medical Language System (UMLS). That repo will be public in the next 1-2 weeks. 

Hope this helps! Happy to answer any other questions.

**Comment by rjurney** [comment]
@jason-fries was this code you mention released?

**Comment by sebastianpretzer** [comment]
> @jason-fries was this code you mention released?

I believe this is it: https://github.com/som-shahlab/trove
