### ISSUE TITLE
Increase minimal supported scikit-learn version

### ISSUE THREAD

**Issue by rth** [snorkel-team/snorkel#1613]
Currently snorkel requires scikit-learn <0.22, while the latest version if 0.23.2 with 0.24 on the way.
As far as I can tell only scikit-learn imports are metric related modules and those should not change in a backward incompatible way.

It might be better to indicate <1.0 as an upper bound for scikit-learn. Scientific python packages don't follow semver anyway and put a lot of effort to not break backward compatibility (at least not without a deprecation cycle first).

**Comment by brahmaneya** [comment]
Hi @rth , we periodically update versions for dependencies. We can update the requirement to <0.24 in our next version. If you are in a hurry, feel free to send a PR to bump the version as well!
