### ISSUE TITLE
Understanding the equation in Data Programming: Creating Large Training Sets, Quickly.

### ISSUE THREAD

**Issue by pratikchhapolika** [snorkel-team/snorkel#1614]
I was going through the official paper << https://arxiv.org/pdf/1605.07723.pdf>> and came across this two equations:

![ratner_doubt2](https://user-images.githubusercontent.com/11159549/93998126-c6870e80-fdb1-11ea-8a46-10907b0a453c.png)

Here are my doubts regarding equation 1:

1. What does   ![equation1](https://user-images.githubusercontent.com/11159549/93998513-41502980-fdb2-11ea-93e4-787186e8b137.png) means in  **equation 1**? And what is value of **Y,** is it just {-1,1} or entire true labels of data in data-set?
2. The final value of **equation 1** will be just a number, right?
3. How would I read this equation in mathematical way?

I will add more question once these 2 are clarified?

**Comment by brahmaneya** [comment]
Hi @pratikchhapolika , the term in your first question is an indicator function for the i^{th} labeling function voting the same as the true label Y. i.e. it evaluates to 1 if the labeling function  term Y is one of -1 and 1. The final value is indeed a number, the product of all the probabilities.
