### ISSUE TITLE
Error while importing snorkel.learning

### ISSUE THREAD

**Issue by shantanuaggarwal2695** [snorkel-team/snorkel#1617]
## Issue description

I am unable to import snorkel.learning module due to assertion error in a numbskull package

## Code example/repro steps

import numbskull

Error: 
def __init__(self, module, ftype, name):
--> 594         assert isinstance(ftype, types.Type)
    595         super(Function, self).__init__(module, ftype.as_pointer(), name=name)
    596         self.ftype = ftype

AssertionError: 

## Expected behavior
The package should get imported 
## Screenshots

![Screenshot from 2020-10-07 03-02-25](https://user-images.githubusercontent.com/29815001/95298287-d985ee00-0849-11eb-8ada-72d8d62f5433.png)
![Screenshot from 2020-10-07 03-02-12](https://user-images.githubusercontent.com/29815001/95298310-e1de2900-0849-11eb-97f4-b95aa2c32e01.png)

## System info

* How you installed Snorkel (conda, pip, source): Conda
* Build command you used (if compiling from source): 
* OS: Ubuntu 19.04
* Python version: python 3.6
* Snorkel version: 0.7.0b0
* Versions of any other relevant libraries:

**Comment by ajratner** [comment]
This is not the current version of `snorkel`- numbskull has not been a dependency for several years.  I would try upgrading to the current version!
