### ISSUE TITLE
Is there any documentation for HTMLDocPreProcessor ? Can I use it to parse HTML Document

### ISSUE THREAD

**Issue by riteshbathwal** [snorkel-team/snorkel#1618]
It would be helpful to understand how I can use the class HTMLDocPreProcessor of snorkel to parse a HTML document and get insights from the content of a web page based on the parsing results. Any pointer in this direction will of great help in using the snorkel to create my ML model around HTML Documents

**Comment by bhancock8** [comment]
Snorkel actually doesn't have a `HTMLDocPreProcessor` class. I believe you're thinking of a [class](https://github.com/HazyResearch/fonduer/blob/7e9ebadbff937ba6e39ffed7e08e80d23104c9dd/src/fonduer/parser/preprocessors/html_doc_preprocessor.py) from [Fonduer](https://github.com/HazyResearch/fonduer), a project in the Snorkel family, but with a separate repository.
