### ISSUE TITLE
Intuition understanding each component of overall loss (LabelModel)

### ISSUE THREAD

**Issue by koren-v** [snorkel-team/snorkel#1619]
Hi, I was interested in how LabelModel works, so decided to learn in from code.
So, there are 3 components of loss:
1) [_loss_l2](https://github.com/snorkel-team/snorkel/blob/ed7771812a0484ad593485dc9e7c67091d483e37/snorkel/labeling/model/label_model.py#L506) - probably usual l2 regularization loss that **prevents high parameter values, right?**
2) [loss_1](https://github.com/snorkel-team/snorkel/blob/ed7771812a0484ad593485dc9e7c67091d483e37/snorkel/labeling/model/label_model.py#L546). Do I understood correctly, that this loss responsible for **making the correlation between parameters of each Label Function similar to their covariation matrix O** (+taking in account class balance)?
3) [loss_2](https://github.com/snorkel-team/snorkel/blob/ed7771812a0484ad593485dc9e7c67091d483e37/snorkel/labeling/model/label_model.py#L547). Finally, does this loss responsible for **making parameters high if the coverage (density) of Label Function is high too**?

**Comment by fredsala** [comment]
Hi Vitaliy---I answered your question on our chat; see

https://spectrum.chat/snorkel/help/intuition-understanding-each-component-of-overall-loss-labelmodel~eac10293-ccc6-4367-a908-9edec805b729
