### ISSUE TITLE
Bump scikit-learn version to 0.23.x

### ISSUE THREAD

**Issue by sebnyberg** [snorkel-team/snorkel#1620]
The latest version of Snorkel (v0.9.6) depends on 

```
scikit-learn>=0.20.2,<0.22.0
```

Scikit-learn has a build dependency on Cython, but did not declare it until 0.23.0 (see [this issue](https://github.com/scikit-learn/scikit-learn/issues/15298) merged in [this PR](https://github.com/scikit-learn/scikit-learn/pull/16244)).

As a consequence, poetry is currently unable to install snorkel unless cython is first [installed with pip](https://github.com/python-poetry/poetry/issues/1241#issuecomment-587535550).

To replicate:

```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
poetry init ...
poetry add snorkel@0.9.6 # fails
```

Error:

```
Installing collected packages: scikit-learn
    Running setup.py install for scikit-learn: started
    Running setup.py install for scikit-learn: finished with status 'error'
[...]
      File "/private/var/folders/b6/_wl34dtj7dg5qs_kc7463msh0000gn/T/tmp.4dr7oreo/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/utils/setup.py", line 8, in configuration
        from Cython import Tempita
    ModuleNotFoundError: No module named 'Cython'
```

**Comment by rjurney** [comment]
@paroma @brahmaneya this means Snorkel doesn't build for many people.
