### ISSUE TITLE
How to replicate snorkel notebook tutorial in local machine?

### ISSUE THREAD

**Issue by pratikchhapolika** [snorkel-team/snorkel#1622]
Hi  @ajratner, @paroma 

I am using this link to learn Snorkel's tutorial of You Tube comments classification.

https://github.com/snorkel-team/snorkel-tutorials/blob/master/spam/01_spam_tutorial.ipynb

Steps that I followed:

`pip install snorkel
! python -m spacy download en_core_web_sm`

When I trid running this line: `from utils import load_spam_dataset`

It's giving error 

`ModuleNotFoundError`              

`Traceback (most recent call last)`
`<ipython-input-4-e910dfd303ce> in <module>`
`----> 1 from utils import load_spam_dataset`
`ModuleNotFoundError: No module named utils`

**How can I replicate the notebook in my Windows local machine?**

When I downloaded snorkel package it's showing me this folders:

![image](https://user-images.githubusercontent.com/11159549/103991115-434ec480-51b8-11eb-8dad-337561e6883a.png)

Under **utils** I can't find any l**oad_spam_dataset** function.

**Question: Can you someone guide me step by step of replicating this tutorial in local jupyter notebook**

**Comment by vincentschen** [comment]
Hi @pratikchhapolika - thanks for your question! Can you try cloning and running the tutorial from this repository? https://github.com/snorkel-team/snorkel-tutorials/tree/master/spam
