### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by danielgil1** [snorkel-team/snorkel#1623]
will this project continue as open source? I am curious since in README is mentioned the team is focused on Snorkel Flow and I don't see much activity during the last months. Thanks.

**Comment by rjurney** [comment]
My understanding is that while they are focused on the business of getting Flow out, they fully intend to continue to contribute as a vibrant open source Snorkel ecosystem is essential to Snorkel AI's strategy.

**Comment by ivelin** [comment]
I was wondering the same. Awesome project, but it looks like the core team has moved on to the SaaS product. 
There is a [PR open and waiting](https://github.com/snorkel-team/snorkel/pull/1616) for review since October ,2020.

**Comment by henryre** [comment]
Hi all, thanks for the discussion here. Would encourage you to take a look at the [discussion on Spectrum](https://spectrum.chat/snorkel/general/announcing-snorkel-flow~b4a97686-709a-4d46-99f5-4f665e5c989b) as well. We'll be updating the language on the README clarifying how we'll be maintaining the repo going forward.

In general, we intend to be responsive to issues and PRs. It looks like #1616 fell off of our radar, and we'll get to it ASAP.
