### ISSUE TITLE
Show a progress bar on LabelModel.fit

### ISSUE THREAD

**Issue by nbeuchat** [snorkel-team/snorkel#1624]
## Is your feature request related to a problem? Please describe.
When fitting a `LabelModel` with hundreds of labeling functions and thousands of datapoints, it can take several minutes to complete. When calling `fit()` on my `LabelModel`, I currently have no clue how many epochs were already processed nor an estimated ETA (even if `verbose` is set to `True`). 

## Describe the solution you'd like
When calling `LabelModel().fit()`, a `tqdm` progress bar would be displayed and updated after each epoch. This would at least be shown if `verbose=True`

## Describe alternatives you've considered
`time` library and print statements

## Additional context
Snorkel version: `snorkel==0.9.6`
Run in Jupyter lab

**Comment by rjurney** [comment]
Is this possible?
