### ISSUE TITLE
Pandas Panel package deprecated in newer versions

### ISSUE THREAD

**Issue by NaRuecker** [snorkel-team/snorkel#1632]
I updated my pandas version to 1.2.2 and that caused an old snorkel script to fail with the following error:

ImportError: cannot import name 'Panel' from 'pandas' (C:\ProgramData\Anaconda3\lib\site-packages\pandas\__init__.py)

In pandas version 0.25.1 the deprecation was also announced
![image](https://user-images.githubusercontent.com/12310354/108896667-36a8f300-75e3-11eb-80f3-bd16e2b3522d.png)

Updating snorkel to 0.9.6, did not help either, so I'm assuming there is no workaround, yet.

Below a code sample:
```python
from snorkel.labeling import PandasLFApplier

ABSTAIN = 0
NonDog = 0
Dog = 1

@labeling_function()
def dog(x):
    return Dog if "dog" in x.text.lower() else ABSTAIN

lfs = [dog]

applier = PandasLFApplier(lfs)

def AddLabels(df, applier):
    df['Text']=df['Description']
    L_CoreData = applier.apply(df=df)
    print(L_CoreData.shape)
    COLUMNS=['dog']
    
    labels_df= pd.DataFrame(L_CoreData, columns=COLUMNS)
    print(labels_df.shape)
    print(df.shape)
    df=df.reset_index()
    return(df)

labeled_data=AddLabels(data, applier)
```
This results with this error: 
![image](https://user-images.githubusercontent.com/12310354/108898411-2c87f400-75e5-11eb-82eb-ab5071e2fd6b.png)

**Comment by bhancock8** [comment]
Hi Nadine, I was able to get your code above to work after (a) changing the field name from "Text" to "text" (to match its usage in the @labeling_function—in the future, a small sample payload would be helpful), and (b) updating my numpy version. So I'm running (on linux) with snorkel==v0.9.6, numpy==1.16.5, pandas==1.2.3. PR #1633 should address this in a permanent way, but in the meantime see if updating your environment as described above unblocks you.
