### ISSUE TITLE
More flexibility with tensorboard library version

### ISSUE THREAD

**Issue by karimtemsah** [snorkel-team/snorkel#1657]
## One will not be able to use this library along with tensorflow due to conflicting transitive dependencies
It will be great if you can adapt your code to `tensorboard>=2.0` since this is the one used by `tensorflow` library. Otherwise we will not be able to use `tensorflow` and `snorkel` together in one place

**Comment by humzaiqbal** [comment]
Hi karimtemsah,
Thanks for raising this issue. If you put the proposed changes in a PR, we'd be happy to review!

**Comment by hardianlawi** [comment]
@humzaiqbal I made a PR related to this. Could you please help review it? Thank you
