### ISSUE TITLE
Error in save LabelModel with pickle

### ISSUE THREAD

**Issue by meidata** [snorkel-team/snorkel#1658]
## Issue description

I have trouble saving a LabelModel trained with `lr_scheduler='linear'`

## Code example/repro steps

I have a label_model trained with the following params:
`label_model.fit(L_train=L_train, n_epochs=500, lr=0.001,lr_scheduler='linear', optimizer='adam',log_freq=100, seed=123) `

But when I tried to save the model on the disk by pickle, I got the following error:

`label_model.save('./test_save.pickle')`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_19655/3895809973.py in <module>
----> 1 label_model.save('./test_save.pickle')

~/.virtualenvs/zd_cls/lib/python3.7/site-packages/snorkel/labeling/model/base_labeler.py in save(self, destination)
    124         """
    125         f = open(destination, "wb")
--> 126         pickle.dump(self.__dict__, f)
    127         f.close()
    128 

AttributeError: Can't pickle local object 'LabelModel._set_lr_scheduler.<locals>.<lambda>'
```

## System info

* How you installed Snorkel (conda, pip, source): pip install 
* Build command you used (if compiling from source): None
* OS: Linux
* Python version: 3.7.5
* Snorkel version: 0.9.7
* Versions of any other relevant libraries: None

**Comment by humzaiqbal** [comment]
Hi meidata,
Thanks for raising this issue! We were able to reproduce it—the issue appears to be stemming from the fact that the LambaLR scheduler includes a lambda function, which doesn't pickle well. One solution to this is to replace that lambda function with a class. We'll put together a PR to address this and link it to this issue so you can see when it's merged.
