### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions'  for Python3.9

### ISSUE THREAD

**Issue by keesjandevries** [snorkel-team/snorkel#1667]
When I run
```
from snorkel.labeling.model import LabelModel
```
Using Python3.9, I get this error
```
ImportError: cannot import name 'gcd' from 'fractions' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```
It seems to be a bug in `networkx`, cf. [this discussion](https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions).

As a workaround I'm rolling back to Python3.8, but this is obviously not ideal.

**Comment by humzaiqbal** [comment]
Hi keesjandevries,

Our repo only officially supports Python 3.8 or lower. If you want to set up an environment that will have all the right packages and dependencies you can run tox. See the `Development Environment` section of https://github.com/snorkel-team/snorkel/blob/master/CONTRIBUTING.md for more reference

**Comment by dataqa** [comment]
I fixed this by importing `networkx==2.5`. Can you not relax the requirement?

**Comment by dataqa** [comment]
Please don't go stale.

**Comment by bhancock8** [comment]
Thanks for the note, @dataqa. I know we've had issues with the networkx package in the past (e.g., it hasn't always adhered to semantic versioning, introducing non-backward compatible changes between minor versions), but we'll take a look and see if `networkx==2.5` is feasible.

**Comment by rsmith49** [comment]
Hi @dataqa! According to [setup.py](https://github.com/snorkel-team/snorkel/blob/master/setup.cfg) we currently support using `networkx==2.5`. Let us know if you still have trouble using it!

**Comment by dataqa** [comment]
Worked like a charm! Thanks so much :-)
