### ISSUE TITLE
When is the new release scheduled?

### ISSUE THREAD

**Issue by hardianlawi** [snorkel-team/snorkel#1669]
Hi, is there any plan for a new release? The latest release was in March and since then, I think there have been quite a number of bug fixes here and there which would be really helpful.

Thank you! :)

**Comment by hardianlawi** [comment]
Any news @rsmith49 ?

**Comment by humzaiqbal** [comment]
Hi hardianlawi,

The new release has been cut for [v0.9.8](https://github.com/snorkel-team/snorkel/releases/tag/v0.9.8). 

Hope this helps!
