### ISSUE TITLE
Value of mu for a particular LF depends on 3 LFs only or on all LFs?

### ISSUE THREAD

**Issue by mayankgoyal1993** [snorkel-team/snorkel#1678]
Why does the value of mu for a particular LF change as we keep adding more LFs, given the value of mu for a particular LFs should not depend on other LF if a minimum of 3 LFs conditions is satisfied?

**Comment by rsmith49** [comment]
Hi @mayankgoyal1993! The label model uses all available LFs for the estimation of mu (3 is merely the minimum required number, not an upper limit on how much information the label model will use). Hope that helps!

**Comment by mayankgoyal1993** [comment]
Thanks for the response, but does that mean the equation has more than one solution that we are solving for all available LFs as only solving 3 LFs can also give the solution and the less LFs equations remain same when we use high number of LFs.

**Comment by humzaiqbal** [comment]
Hi @mayankgoyal1993 ,
You can think of this as similar to solving an overdetermined linear system. While we can use fewer equations to solve, using all available equations will reduce the noise the most. Further approaches have studied just using three equations at a time. More information here:  http://cs229.stanford.edu/notes2019fall/weak_supervision_notes.pdf 

Hope this helps!
