### ISSUE TITLE
Multi-label semantic segmentation using Snorkel ?

### ISSUE THREAD

**Issue by tgrippa** [snorkel-team/snorkel#1679]
Hi all,

I'm working on weak supervision of DL network (Fully convolutional networks) for multi-label semantic segmentation task. So, the idea is to assign a label (several labels possibles) to each pixels of my images. Is it possible and/or is there some example of use of Snorkel to deal with this task ? From what I see on the tutorial repository and around the Internet, it seems there is no example of such. I found [the article about Coral](https://www.snorkel.org/blog/coral) but it is about VQA and not semantic segmentation :/

Cheers,

**Comment by fredsala** [comment]
Hi Grippa,

We've had success applying weak supervision to image segmentation; see this paper for our work on this problem: https://openreview.net/pdf?id=bjkX6Kzb5H

Cheers,
Fred
