### ISSUE TITLE
No LF for negative class in NER/ high LF overlap

### ISSUE THREAD

**Issue by anjani-dhrangadhariya** [snorkel-team/snorkel#1691]
## Issue description

Snorkel is really the coolest stuff I've used. Kudos to the creators. I am working on a NER problem using Snorkel. NER is usually a class imbalanced problem with only a few tokens being positive entities and the rest being out-of-the-span entities. I have several labeling functions that label each token in a sequence either with class label 1 or abstain label -1. I do not have any labeling functions that specifically mark a token as a negative entity class (0). What I do in this case is that if an LF cannot label a token with either -1 or 1, it is marked as 0. In this case, all my labeling functions achieve true negative rates (TNR) between 98% and 99% (with only one LF having a TNR of 80.25%). However, when the LF overlap is calculated, it also turns out to be between 97%-99% for many LF's which might have an impact on the label model. I am using snorkel version 0.9.7 and presume from [here](https://github.com/snorkel-team/snorkel/blob/718847f782a3cc90c22b33318b2bf649f4ccded3/snorkel/labeling/model/label_model.py) that it considers each LF as conditionally independent given a true unobserved label Y. So high overlap might not be an issue in this case?

## System info

* Snorkel version: 0.9.7​

**Comment by vkrishnamurthy11** [comment]
Thanks for the kind words, @anjani-dhrangadhariya . We hope you enjoy using Snorkel as well!

With regards to your question, high overlap will not be an issue. Typically LF overlaps are what allow the label model to actually learn and come up with a signal. And yes, we are making the conditional independence assumption as well.
