### ISSUE TITLE
When a token does not fall under any of the class labels or abstains in NER?

### ISSUE THREAD

**Issue by anjani-dhrangadhariya** [snorkel-team/snorkel#1692]
## Issue description

I have a program that labels a sequence of words using ontologies. I have labeling functions for class negative, class positive, and class abstain. Should I keep the word unlabeled if it does not fall under any of these class labels and ignore it or should I force-label them under either class negative or abstain? I will be grateful for any hints or help.

**Comment by humzaiqbal** [comment]
Hi anjani-dhrangadhariya,

Thanks for reaching out! To clarify you explicitly want 'abstain' as a class as opposed to just considering cases where labeling functions don't vote to be abstaining correct? 

If thats the case, I don't think you need to force-label in the case where no labeling functions vote on a given word. Probabilistic labels will still be generated anyway (the fact that no labeling functions voted is itself a signal the label model picks up on).

Hope this helps!

**Comment by anjani-dhrangadhariya** [comment]
> 



> Hi anjani-dhrangadhariya,
> 
> Thanks for reaching out! To clarify you explicitly want 'abstain' as a class as opposed to just considering cases where labeling functions don't vote to be abstaining correct?
> 
> If thats the case, I don't think you need to force-label in the case where no labeling functions vote on a given word. Probabilistic labels will still be generated anyway (the fact that no labeling functions voted is itself a signal the label model picks up on).
> 
> Hope this helps!

Thanks for writing, Humza. For my entity recognition application, I abstain on a specific list of words and label positive (+1) on a specific list of words. So not sure if 'abstain' becomes a class here. I do not have such a list for the negative class (-1). But I gain from your reply that even in this case, probabilistic labels will be generated. Please correct me if I am wrong.

**Comment by anjani-dhrangadhariya** [comment]
> Hi anjani-dhrangadhariya,
> 
> Thanks for reaching out! To clarify you explicitly want 'abstain' as a class as opposed to just considering cases where labeling functions don't vote to be abstaining correct?
> 
> If thats the case, I don't think you need to force-label in the case where no labeling functions vote on a given word. Probabilistic labels will still be generated anyway (the fact that no labeling functions voted is itself a signal the label model picks up on).
> 
> Hope this helps!

Thank you for your answer, Humza! I removed my previous response as it came from a different understanding. I am not using abstain class and just use abstain as a label where none of the labeling functions voted. The problem was that I did not have any negative label LFs. To make the label model work, I need to have labeling functions that emit non-zero labels {-1, 1}.
