### ISSUE TITLE
Support for M1 Mac

### ISSUE THREAD

**Issue by zexuan-zhou** [snorkel-team/snorkel#1695]
## Support for M1 Mac
Just want to bump this issue up again: https://github.com/snorkel-team/snorkel/issues/1689
There has been a PR but seems not building: https://github.com/snorkel-team/snorkel/pull/1690

Can anyone from the dev team take a look? Appreciate it

## Describe the solution you'd like
Loose numpy version so that the package can be installed on M1 Mac

## Describe alternatives you've considered
I don't think there is a easy way to get around with this unless using an Intel Mac

## Additional context
None

**Comment by zexuan-zhou** [comment]
@ajratner @henryre @stephenbach @bhancock8

**Comment by rsmith49** [comment]
@zexuan-zhou there are still a few type checking issues that I haven't had a chance to dig into on #1690. If you would like to contribute, we'd be happy to approve and merge! Otherwise, we'll get to fixing those last few issues later in the week and update you here when it has been merged.

**Comment by zexuan-zhou** [comment]
@rsmith49 I'm happy to contribute. I tried to create a branch and push but I get this error:
```
fatal: unable to access 'https://github.com/snorkel-team/snorkel.git/': The requested URL returned error: 403
```
Do I need to get authentication from you guys?

Thanks

**Comment by zexuan-zhou** [comment]
@rsmith49 @bhancock8 Please take a look at this PR: https://github.com/snorkel-team/snorkel/pull/1698
I tested it under py38 on M1 Mac and need some help on tests in other envs and CICD.
Thank you

**Comment by rsmith49** [comment]
@zexuan-zhou this should be good to go, thanks for the help!

I'm going to close this issue, but feel free to open a new one if numpy on the M1 isn't working properly.
