### ISSUE TITLE
When will snorkel officially releases 0.9.9 version on conda?

### ISSUE THREAD

**Issue by yinxiangshi** [snorkel-team/snorkel#1704]
I've been waiting for 0.9.9 on conda for long days, I wonder what's wrong with new version release, I can do a little favor.

**Comment by humzaiqbal** [comment]
Hi yinxiangshi and RadionBik,

Apologies for the delay here, need to resolve some CI issues before the release can be cut which are currently being worked on. Will update here once it has been. Thanks for the patience!

**Comment by rjurney** [comment]
#abandonware

**Comment by cerquide** [comment]
Since I needed it myself, I have repackaged snorkel into pip package [snorkel2](https://pypi.org/project/snorkel2/). No changes to the library, just removed requirements which were making the library obsolete. Right now can only be installed by pip. 

```
pip install snorkel2  
```

The github is [here](https://github.com/cerquide/snorkel/), you can get in touch with me in the [Snorkel2 discussions board](https://github.com/cerquide/snorkel/discussions/)

**Comment by bhancock8** [comment]
Apologies for the delay! The repo was in dependency and CI hell there for a bit, but resolved now. Dependencies have been updated for most libraries. v0.9.9 has been cut (PR #1700) and pushed to pypi (https://pypi.org/project/snorkel/). It should be available on conda within a day or so (I'll respond here again and close the issue when it is). 

We previously had upper bounds on most dependencies on purpose for stability reasons, but have decided to leave them open to higher versions moving forward for better forward compatibility, so there should be fewer issues like this moving forward. It's an open area of debate which is better practice (see https://iscinumpy.dev/post/bound-version-constraints/ for some relevant discussion on the topic), but the latter seems like the appropriate choice for now. Thanks again everyone for your patience!

**Comment by rjurney** [comment]
@bhancock8 thank you so much for cutting a release and addressing all of the issues it solves! It was quite difficult to use snorkel before this release due to stale dependencies and I think this will address the problem :)

**Comment by cerquide** [comment]
@bhancock8  thanks for preparing the new release. Since snorkel is back, I have removed snorkel2 from Pypi to avoid polluting the Python ecosystem.

**Comment by bhancock8** [comment]
Thanks @cerquide! And if there are ever specific libraries that need updating and you're able to make a PR that passes tests, that's a super efficient way for us to review and merge things much faster. Per the above, hopefully the new policy of leaving open ended upper bounds makes such PRs necessary less frequently as well.

**Comment by bhancock8** [comment]
v0.9.9 is now on conda (https://anaconda.org/conda-forge/snorkel)—I'm going to mark this issue as resolved.
