### ISSUE TITLE
ModuleNotFoundError: No module named 'snorkel.learning',how to solve it?

### ISSUE THREAD

**Issue by LN-sys** [snorkel-team/snorkel#1717]
![image](https://user-images.githubusercontent.com/52775089/201354288-f4f9ce82-8b2f-432b-9fa4-4d52fabeada7.png)

**Comment by bhancock8** [comment]
That looks like code from the `snorkel-extraction` repo: https://github.com/snorkel-team/snorkel-extraction. Take a look there and reopen this if that doesn't resolve your question.
