### ISSUE TITLE
Snorkel Coral for melanoma sementation classification

### ISSUE THREAD

**Issue by MaithaAlmushtaghil** [snorkel-team/snorkel#1727]
Hello Snorkel Team,

I have worked before on snorkel for sentiment analysis over text and I am now interested in working with Snorkel coral for image inputs.
The project I want to work on is given skin cancer images and their segmentation, I want to produce 2 labels of "Melanoma" and "No melanoma".
I have read the paper of "Inferring Generative Model Structure with Static Analysis" and I am interested on experimenting Coral however, I can not seem to be able to find any open source repositories on Coral. And from this issue: https://github.com/snorkel-team/snorkel/issues/802 I found I need to be added to a private repo.

I would appreciate it if I could get access to the repo or how to use snorkel for labeling segmentation masks.

**Comment by paroma** [comment]
You can check out the image tutorial here: https://github.com/snorkel-team/snorkel-tutorials/tree/master/visual_relation which might be similar to what you're looking for. Hope it helps!
